### ISSUE TITLE
Use `null` as a pattern for not setting values

### ISSUE THREAD

**Issue by dalgard** [thoughtbot/neat#113]
With the mixin `pad()`, any previously set padding in the cascade is overridden, since it simply outputs `padding: ...`. I've defined my own mixins such as `pad-sides` and `pad-vertical`, but what I'd really like to do is take the nice syntax of `pad` but pass `null` for values that should not be set. Example:
```
@include pad(0 null null default);

// outputs
padding-top: 0;
padding-left: flex-gutter();
```
The mixin should be intelligent enough to simply output `padding: ...` if all four values are set. This pattern of using `null` to declare that the output should __not__ contain any overriding rules for this value should be used throughout the framework.

**Comment by whmii** [comment]
Unless I am mistaken, this need has been addresed. Closing for now
