### ISSUE TITLE
Feature: Fractions in span-columns

### ISSUE THREAD

**Issue by paulozoom** [thoughtbot/neat#131]
Most of the time when designing in the browser, I think of using my grid in terms of halves, thirds, and fourths, mostly I find these the more useful and versatile divisions of a 12-unit grid.

While doing `span-columns(4)` isn’t a problem at all, I find it sometimes unnatural to do when thinking in terms of halves, thirds, and fourths. Plus, when reading the code, developers need to have and maintain a knowledge of how many units this current grid has.

So my proposal is allowing fractions as `@include span-columns(1/4);`. In practice, this would be no different than doing `@include span-columns(1/4*$grid-columns);`

**Comment by whmii** [comment]
This is an interesting feature, as it stands this will probably not be included. It has the potential to have 2 ideas be conflated.

1. `@include span-columns(1/4);` meaning 1 out of 4 of the total space
1. `@include span-columns(1/4);` meaning 0.25, meaning 1 fourth of 1 column
