### ISSUE TITLE
Target multiple breakpoints

### ISSUE THREAD

**Issue by samueljseay** [thoughtbot/neat#132]
Hey, hope this isn't a dumb question. I'd really love to be able to do:

$mobile: new-breakpoint(...)
$custom: new-breakpoint(..)

@include media($mobile,$custom) {
  //some styles
}

Is there a way to achieve this currently? I looked at the docs but it doesn't appear to be possible. Thanks so much for your time. Bourbon Neat is the best thing since sliced bread! xoxo.

**Comment by cmnstmntmn** [comment]
what about @samueljseay request, any updates?

**Comment by grrowl** [comment]
+1 I'm in the same boat, the current neat library doesn't seem to [address this in a way that also supports `new-breakpoint`](https://github.com/thoughtbot/neat/blob/master/app/assets/stylesheets/grid/_media.scss#L25). I'll have to keep 12 columns across breakpoints and define the column span in individual locations instead.

**Comment by mbesto** [comment]
+1 here

**Comment by renatodex** [comment]
+1, that should REALLY be implemented!

**Comment by kaishin** [comment]
We'll be accepting PR's if anyone wants to implement this.

**Comment by cmnstmntmn** [comment]
https://github.com/postcss/postcss

**Comment by kaishin** [comment]
@cmnstmntmn Not sure that's helpful.

**Comment by samueljseay** [comment]
Hey guys, still need to add column support and all the rest but would something like this be headed in the right direction?

http://sassmeister.com/gist/663615b7ddbd80965d84

**Comment by RazzyJohnson** [comment]
+1

**Comment by arkjoseph** [comment]
+1

**Comment by whmii** [comment]
Some great comments here. Since we are working on further changes, I'm going to close this for now.
