### ISSUE TITLE
Trouble getting a 3x3 grid

### ISSUE THREAD

**Issue by WilsonAus** [thoughtbot/neat#153]
![screen-shot-2014-02-21-at-2 51](https://f.cloud.github.com/assets/3875994/2227537/d137204c-9ac4-11e3-8e18-13912b609d0f.jpg)
 
I am trying to get the full-width 3x3 grid but can not seem to get it to work... it ends up like above using the below neat includes.

HTML:
![screen shot 2014-02-21 at 2 57 47 pm](https://f.cloud.github.com/assets/3875994/2227559/80178732-9ac5-11e3-9289-29b9408010ca.png)

My neat includes look like so:

.home-grid {
	.moduletable { 
		@include span-columns(4, block-collapse); 
	}
}

**Comment by kaishin** [comment]
I gave this some thought and I think it's not worth the substantial effort required to solve it. The `block-collapse` feature was an afterthought and is meant to be used in isolated cases where some elements are collapsed while their siblings are not. If your goal is a gutterless 3-column layout then use CSS percentages instead. Flexbox seems like a good alternative too.

**Comment by makabde** [comment]
I was facing the same issue and I came up with the following solution to make it work:
```scss
.feature {
  @include span-columns(4);

  &:nth-child(3n) {
    @include omega();
  }
}
```
Hope this helps.

**Comment by makabde** [comment]
I was facing the same issue and I managed to get it working with the following:
```scss
.feature {
  @include span-columns(4);

  &:nth-child(3n+1) {
    @include omega();
  }
}
```
Hope this helps.

**Comment by amitrh** [comment]
I am getting the 3x3 grid properly on large system But when i'm using media for small device then it not  get 2x2 grid properly. 

	section.tuts-list-item-container {
		@include clearfix;
		@include outer-container;
		@include margin(20px null null null);

		.tuts-list-item {
			@include clearfix;
			@include span-columns(4);
			background-color: #ffffff;
			min-height: 440px;
			@include omega(3n);
	    	overflow: hidden;

		    @include media(min-width 320px max-width 992px) {
		      @include span-columns(6);
		      @include omega(2n);
		    }
		}
	}

![screenshot](https://s3.amazonaws.com/redpen-prod/red-pen-c79a0d18-c0c3-4ebc-a5e8-d4664d5bad13.png)

![screenshot](https://s3.amazonaws.com/redpen-prod/red-pen-4e20e96b-58b1-4a32-b1bd-cdc939c05f82.png)
Please Help me.

**Comment by philn5d** [comment]
// ----
// Sass (v3.2.14)
// Compass (v0.12.3)
// Bourbon (v3.1.8)
// Neat (v1.5.0)
// ----

@import bourbon/bourbon
@import neat/neat

$grid-columns:3

.home-grid
  @include row

.moduletable
  @include span-columns(1)
  @include omega(n)
  background-color: red

**Comment by philn5d** [comment]
http://sassmeister.com/gist/9676277a1064f4ef3368
