### ISSUE TITLE
Override the default $gutter variable for different grids / span-columns()

### ISSUE THREAD

**Issue by ghost** [thoughtbot/neat#187]
Good afternoon,

I am trying to create a grid using the span-columns, which works absolutely fine. My problem is that the gutter/margin between each grid item is too large. My client would like the gutter between each item to be smaller.

e.g. 
<code>
@include span-columns(3 of 9);
</code>
This will output a margin of margin-right: 2.06186%, however, I would like this margin to be something like 1%.

Any ideas?

Thanks

**Comment by ryanburnette** [comment]
@kaishin Has this feature made its way into a release yet?

**Comment by ryanburnette** [comment]
#96
