### ISSUE TITLE
Grid side margins

### ISSUE THREAD

**Issue by philippebarbosa** [thoughtbot/neat#188]
Hi all,
why does Neat doen't have a margin on both side of the outer-container ?
When browser is smaller than the `$max-width` size, and before the first breakpoint, it cause some ugly layout, because the website doesn't have space on sides.

[Screenshot from neat.io](http://barbo.sa.com/2ih8/3dybKwrj)

Many grid provides that feature, as the (old and) famous 960gs, which is 940 + 20px margin.

What I did to to fix that :
A `.wrap` div which has the `$max-width` and `$gutter x 2` size, with `padding: 0 $gutter;`. (with `border-box` box-model).

Maybe not the best solution…would you recommand something better ?

Thanks a lot for you help !

**Comment by aendre** [comment]
I had the same issue. @philippebarbosa thanks for a proposed solution!
