### ISSUE TITLE
Merge span-columns and omega mixins

### ISSUE THREAD

**Issue by kaishin** [thoughtbot/neat#203]
This seemed to me like an idea that could improve the syntax and simplify the number of mixins to remember even further. Here's what it could look like:

```scss
@include span-columns(6, auto); // Same result as calling omega()
@include span-columns(6, last); // Effectively removing gutters on that specific element
@include span-columns(2, 2n); // Same result as calling omega(2n)
```
@thoughtbot/design Any thoughts?

**Comment by whmii** [comment]
due to behavior changes, it is unlikely there will be an "omega" in 2.0

is it cool if I close this?
