### ISSUE TITLE
Remove span-column(12) from table-grid example

### ISSUE THREAD

**Issue by CWSites** [thoughtbot/neat#208]
`@include span-columns(12);` shouldn't have a right-margin. We shouldn't have to include omega every time we want to use a full width column. I would have made the update myself and submitted a PR but I couldn't figure out how to update the code accordingly.

I'm guessing this hasn't been an issue before now because the margin doesn't break anything, however it does flow outside of the outer container.

![screen shot 2014-08-05 at 3 17 09 pm](https://cloud.githubusercontent.com/assets/1242102/3817137/29cc5564-1cd5-11e4-95e3-16f6af335589.png)

**Comment by mehlah** [comment]
Looks like this can be closed as fixed. 
I'm doing some [gardening](http://words.steveklabnik.com/how-to-be-an-open-source-gardener) here :) /cc @tysongach
