### ISSUE TITLE
Add gutter margin for :last-child

### ISSUE THREAD

**Issue by tillkruss** [thoughtbot/neat#215]
We're have one element containing 2 `span-columns()`. We want to change their visual order, keeping the HTML structure as it is. The first element has `float: right;` making the last/second show left of the first element.

We're using `omega()` to remove the `margin-right` of the first element. The issue is that the visually first element gets the `:last-child` selector setting it's `margin-right` to `0`. What's the best way of restoring/setting that margin?

**Comment by wardpenney** [comment]
Hi @tillkruss, have you tried using [shift](http://thoughtbot.github.io/neat-docs/latest/#shift) to perform the reordering? 

Also mentioned in this issue https://github.com/thoughtbot/neat/issues/313

**Comment by tillkruss** [comment]
That's how we solved it in the end. Thank you!
