### ISSUE TITLE
Visual Grid as a mixin

### ISSUE THREAD

**Issue by aubricus** [thoughtbot/neat#222]
Hey Neat Team!

As we know, Imports in SASS are pretty limited (as in, it's pretty easy to end up with a bunch of duplicated css if you're not careful). More often than not, I have a multi-paged setup where I've created a _common.scss (or something similar) to aggregate all the "non-generating-scss" in my build; so I can distribute it to all of my files.

When setting `$visual-grid: true`; it dupes the visual grid all over the place. Not a huge deal; as it's a debug setting; but would be nice if it didn't do that.

Creating this issue to gauge general interest. It was simple enough to dupe the contents of the check in **_visual-grid.scss** into something like **@mixin create-visual-grid() {...}**

Maybe this is upcoming in 2.0. Feel free to close. 

Thanks!

P.S.

If its coming in 2.0; I am running, 1.5.1 because Compass still packs SASS 3.2.x.

**Comment by whmii** [comment]
We are working on updating the visual grid. Closing for now
