### ISSUE TITLE
Setting new breakpoint in grid settings ignores column input.

### ISSUE THREAD

**Issue by n0rmand0** [thoughtbot/neat#227]
After doing a bundle update, all our projects seem to ignore the column input in the grid settings.  The entire site reverts back to the default 12 columns.

The only way I could fix this is by manually going back to all my spans and changing them.  i.e." @include span-columns(3 of 6);" " instead of @include span-columns(3);"

I am guessing this is an incompatibility with the latest Compass or Sass ???  These were a couple of the gems which were updated during the bundle install.

**Comment by wardpenney** [comment]
Fantastic @n0rmand0 thank you trying it out in the latest! I'm going to close the issue now. Thanks everyone.
