### ISSUE TITLE
Neat's display mixin overrides Bourbon's display(flex) mixin

### ISSUE THREAD

**Issue by levinelson** [thoughtbot/neat#228]
Bourbon has a handy [flexbox mixin](https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/css3/_flex-box.scss#L66) that uses the syntax `@include display(flex)` and outputs CSS like `display: flex`, `display: -webkit-flex` and so on.

Unfortunately, it looks like Neat's [display mixin](https://github.com/thoughtbot/neat/blob/master/app/assets/stylesheets/grid/_display.scss#L21) overrides the original Bourbon version. If you include Neat after including Bourbon in your main stylesheet, all instances of `@include display(flex)` are not compiled.

**Comment by okbel** [comment]
Same issue here
