### ISSUE TITLE
Sass compile error in _private.scss

### ISSUE THREAD

**Issue by sassomedia** [thoughtbot/neat#233]
Getting following Sass (v3.4.5) compile error when including Neat (v1.7.0pre) in my project:
/Users/myuser/Sites/mysite/scss/neat/functions/private:41: error: non-terminal statement or declaration must end with ';'

Line 41 in _private.scss is the following:
$parent-columns: $grid-columns !global !default;

Switching the last two vars to:
$parent-columns: $grid-columns !default !global;

seems to resolve the issue and lets the compiler pass.
Thoughts?

**Comment by kaishin** [comment]
This should be fixed now.
