### ISSUE TITLE
Use transparent rather than rgba(0,0,0,0)

### ISSUE THREAD

**Issue by HugoGiraudel** [thoughtbot/neat#236]
https://github.com/thoughtbot/neat/blob/master/app/assets/stylesheets/functions/_private.scss#L60

It's only about code elegance at this point.

**Comment by wardpenney** [comment]
@kaishin @HugoGiraudel I'll see if I can try it out next sit down I get.

**Comment by kaishin** [comment]
I checked and this seems to be no longer an issue as all browsers handle it properly now.

**Comment by HugoGiraudel** [comment]
Yep. :)

**Comment by mehlah** [comment]
Looks like this can be closed as there is no more `rgba(0,0,0,0)` in current master branch.
/cc @kaishin @tysongach
