### ISSUE TITLE
Variable in omega()

### ISSUE THREAD

**Issue by GaryJones** [thoughtbot/neat#244]
This SCSS:

~~~scss
@for $i from 2 through 2 {
	.loop {
		@include omega(#{$i}n);
	}
}

.static {
	@include omega(2n);
}
~~~

produces this CSS: 

~~~css
.loop:nth-child(2n) {
	margin-right: 0;
}

.static:nth-child(2n) {
	margin-right: 0;
}

.static:nth-child(2n+1) {
	clear: left;
}
~~~

i.e. the ruleset with the `clear` doesn't appear when using variable / `@for` loop. The relevant bit of `_omega.scss` is:

~~~scss
@if type-of($query) == number {
    &:nth-child(#{$query}+1) {
      clear: $opposite-direction;
    }
  }
~~~

...so it's limiting it to a number, which also apparently stops variables that are a number from also working.

The use case for this is the desire to do:

~~~scss
@for $i from 2 through 9 {
	.gallery-columns-#{$i} &,
	.gallery-col-#{$i} & {
		@include span-columns((12 / $i));
		@include omega(#{$i}n);
	}
}
~~~

**Comment by rob-bar** [comment]
Same problem here, this is due to the fact that the concatenated version is a string and the other is a number.
```scss
@warn $i; // 1
@warn type-of($i); // number
$n: $i+n;
@warn $n; // 1n
@warn type-of($n); // string
@warn type-of(4n); // number
```
This is checked in _omega.scss on line 82
`@if type-of($query) == number and unit($query) == "n" {`
I think it should be just `unit($query) == "n" {` without the number check

**Comment by whmii** [comment]
`Omega` is one of the more problematic mixins in the library.

We may look to remove this soon.

Closing for now.
