### ISSUE TITLE
Adding `omega()` does not remove the directional margin from a column

### ISSUE THREAD

**Issue by bx2** [thoughtbot/neat#258]
What I was doing:
```scss
.main {
  @include outer-container;
  .content {
    @include span-columns(8);
  }
  .aside {
    @include span-columns(4);
    @include omega();
  }
}
```

What I was expecting: 2 columns next to each other.
What I got was 2 columns with proper width but not positioned next to each other.

After removing `@include omega()` and putting instead `margin-right: 0` everything was fine.

**Comment by kaishin** [comment]
#254 has been merged and I'm not not entirely sure what the problem here is. Closing for now.
