### ISSUE TITLE
Shifting two columns / reverse column order

### ISSUE THREAD

**Issue by klickreflex** [thoughtbot/neat#264]
Hi there,

I'm having a hard time to achieve something rather trivial, so I hope I'm just doing it wrong ;)

I have to elements #main and #sidebar that appear in this order in the markup:

```
<aside id="sidebar">...</aside>
<section id="main">...</section>
```

Now I want #sidebar to appear on the right side of #main. I tried the shift mixin, but it seems to produce a mess as soon as I'm shifting two sibling elements. 

So what I'm basically asking is: is `shift` intended to work like that or am I using it completly wrong? If the latter is the case, is there another way to push/pull columns?

```
#main {
  @include span-columns(8 of 12);
  @include shift(-8 of 12);
}
#sidebar {
  @include span-colums(4 of 12);
  @include shift(4 of 12);
}
```

Cheeers,
Daniel

**Comment by ivanjuras** [comment]
Is it possible to do only in certain media queries?

For example, I want to have this on bigger screens:

    <article> Bla </article>
    <aside> blabla </aside>

But, when I come to smaller screens, I want the order reversed, so that the <aside> block would be on top of the <article> block.
