### ISSUE TITLE
Visual grid locked to first breakpoint

### ISSUE THREAD

**Issue by Jorybraun** [thoughtbot/neat#268]
Hi, i've been having a hell of a time with the visual grid and I would like it because its my first time using neat. 

Basically after initial set up i can set my first break point up to 5 grids then set the rest lets say 8 and 12. 
After setting media queries which im pretty sure i've done wrong. I'm quite confused as to how to initialize the grid with a mobile first approach.  The gird itself is working as to what i can see but there visible grid is none existant because i changed the grid from 5 to 6 on the mobile break point. If this makes any sense. 

also im not sure but bitters added a huge margin. I kinda thought it was like a reset or a base style?

 ok for my layout file where im tyring to set up the grid, I'm sure there is a better way to write this but i cant really find any great examples with media queries: 

.wrapper
....@include outer-container(100%)
........article
        //mobile
........@include media($mobile)
............@include span-columns(6)
        //landescape
........@include media($landscape)
............@include span-columns(6)
        //tablet
........@include media($tablet)
............@include span-columns(8)
        //desktop
........@include media($desktop)
............@include span-columns(12)

.one
....#logo
........margin-top: 250px
........height: 150px
........width: 250px
........@include media($mobile)
............@include span-columns(4 of 6)
............@include shift(2 of 6)
........@include media($landscape)
............@include span-columns(3 of 6)
............@include shift(3 of 6)
............@include size(300 200)
........@include media($tablet)
............@include span-columns(3 of 8)
............@include shift(5 of 8)
........@include media($desktop) 
............@include span-columns(3 of 12)
............@include shift(8 of 12)

This seems a bit obese I would love some advice, but i don't think this is where the issue is.
so on to my grid settings as is tradition.

@import "../neat/neat-helpers"; // or "../neat/neat-helpers" when not in Rails

// Neat Overrides
// $column: 90px;
// $gutter: 30px;
// $grid-columns: 12;
// $max-width: em(1088);

// Neat Breakpoints
$mobile: new-breakpoint(min-width 320px 6);
$landscape: new-breakpoint(min-width 480px 6);
$tablet: new-breakpoint(min-width 760px 8);
$desktop: new-breakpoint(min-width 960px 12);

ok now to the main css

@import "bourbon/bourbon";
@import "base/grid-settings";
@import "neat/neat";
@import "base/base";
@import "layout/layout";

I'm quite new to sass I really prefer it to scss , but yeah if any one can point me in the direction or a tutorial where some one actually uses the grid system in real setting, or tell me how i need to think about it differently would be appreciated

**Comment by kaishin** [comment]
It's a bit clunky, but here is the import definition order you need for the visual grid to take into consideration the other breakpoints:

```scss
@import "bourbon/bourbon";
@import "neat/neat-helpers";

$mobile: new-breakpoint(min-width 320px 6);
$landscape: new-breakpoint(min-width 480px 6);
$tablet: new-breakpoint(min-width 760px 8);
$desktop: new-breakpoint(min-width 960px 12);

$visual-grid: true;

@import "neat/neat";
```
