### ISSUE TITLE
Deprecated code in examples

### ISSUE THREAD

**Issue by allejo** [thoughtbot/neat#272]
As I'm following the examples on the [examples](http://neat.bourbon.io/examples/) page, I noticed that the sample code tosses deprecation warning. Should the examples be updated so it no longer shows deprecated code?

**Comment by laander** [comment]
Specifically `include row(table)` with display context passed throws a warning (and refers to using a display() mixin which i cant seem to find?)

**Comment by mehlah** [comment]
It looks like this is no more a problem. Examples looks good to me.
The `display` mixin mentionned should be `display-context`. PR #365 address it.
