### ISSUE TITLE
Documentation linking to thoughtbot.github.io instead of neat.bourbon.io

### ISSUE THREAD

**Issue by crswll** [thoughtbot/neat#274]
Just something I noticed that confused me a bit.

The Neat logo at http://thoughtbot.github.io/neat-docs/latest/ links to http://thoughtbot.github.io/ instead of http://neat.bourbon.io/

**Comment by graysonwright** [comment]
Good catch, @crswll!

**Comment by mattmischuk** [comment]
+1

**Comment by graysonwright** [comment]
It's fixed now! Thanks for the feedback!
