### ISSUE TITLE
span-columns(4) results in margin-: 2.35765%;

### ISSUE THREAD

**Issue by jenniferhail** [thoughtbot/neat#276]
I have added this to the list items in my grid, but Neat is outputting margin without a direction.

    @include span-columns(4);
    @include omega(3n);

Results:

margin-: 2.35765%;
width: 31.76157%;

I also added $default-layout-direction: LTR !default; to my variables scss file, _base.scss, but that didn't fix it.

**Comment by kaishin** [comment]
I am unable to reproduce this so I will close until further details are provided.

**Comment by danny-englander** [comment]
I just ran into this same issue as well. If I have time, I will create a reduced test case and post in a new issue. FWW, I am using Node-Neat with LibSass so I suspect that might have something to do with it.

**Comment by leefernandes-brave** [comment]
I'm also getting margin-right: 2.35765% in a project using bourbon + neat being compiled by gulp-sass.
