### ISSUE TITLE
Using `figure` elements with `span-columns` mixin results in sadness

### ISSUE THREAD

**Issue by zspencer** [thoughtbot/neat#277]
It appears that mozilla and chrome both have a `margin-before` applied to `figure` elements. This causes the figure to take up a few `em`s more space than expected; breaking the grid :'(

A "workaround" is to remove the `margin-before` css attribute on all figures:

```
figure {
  -moz-margin-before: 0;
  -webkit-margin-before: 0;
  margin-before: 0;
}
```

My thinking is this may be something we want to merge in upstream somehow? Perhaps updating bourbon?

**Comment by kaishin** [comment]
From my perspective, this is a Bitters, or maybe even `normalize.css`, feature.
