### ISSUE TITLE
Nested Grids not possible

### ISSUE THREAD

**Issue by renege** [thoughtbot/neat#283]
Hi,

It would be great to have the possibliity to make nested grids.

Now you can do https://www.dropbox.com/s/kwk3r9ieqk6ipaa/Schermafdruk%202014-12-12%2016.16.53.png?dl=0

But what I want is having the access of the full grid inside a grid.

So for the example: @include span-columns(4 of 12); // instead of 8.

**Comment by kaishin** [comment]
Do you want to do `@include span-columns(4 of 12)` inside a `@include span-columns(8)`?

I think this is confusing and is likely never going to be implemented.
