### ISSUE TITLE
span-columns() with block-collapse option is improperly sizing last column

### ISSUE THREAD

**Issue by ElliotChong** [thoughtbot/neat#284]
The last column in a `span-columns(X, "block-collapse");` call is always slightly smaller than the other columns.

*Offending Code:*
```
    @if $display == collapse or $display == block-collapse {
      width: flex-grid($columns, $container-columns) + flex-gutter($container-columns);

      &:last-child {
        width: flex-grid($columns, $container-columns);
      } 
    }
```

I could be off-base on this, but shouldn't this scenario be as straight-forward as the snippet below? It seems to work as expected in my cursory tests.
```
    @if $display == collapse or $display == block-collapse {
      width: percentage($columns / $container-columns);
    }
```

**Comment by kaishin** [comment]
This behavior is deliberate. `columns/container-columns` is fine but beats the purpose of having a grid to begin with. In the future we would recommend using Flexbox for the best results.

**Comment by granteagon** [comment]
I do not understand this.  The project (which is essentially just a grid) deliberately breaks the grid because why?
