### ISSUE TITLE
$base-line-height

### ISSUE THREAD

**Issue by geoff777** [thoughtbot/neat#287]
I'm getting an undeclared variable ... you are using $body-line-height in a couple of places

I think you should be using $base-line-height?

**Comment by kaishin** [comment]
Are you sure this is the repository you are looking for? Neat has no `body-line-height` in its entire code base.

**Comment by geoff777** [comment]
lol I guess not then. Sorry.

I was playing with Bourbon, Neat, Bitters and Refills.
I did finally get them all playing nicely.
