### ISSUE TITLE
Bourbon version dependency higher than advertised

### ISSUE THREAD

**Issue by grantovich** [thoughtbot/neat#290]
Neat 1.7.0 depends on Bourbon 4.0+, but the README still says that 3.1+ is supported, and the release notes don't seem to mention this change (made at b4b8a1be6c3a4f311b9256720b8797c65d4c89e7). For those still using Bourbon 3 due to `libsass` limitations, this could be a source of confusion. Is it intentional?

**Comment by wardpenney** [comment]
@grantovich I'll have to take a look, it sounds like a bug in the dependencies to me. I'll get back to you when I locate the detail.

**Comment by tysongach** [comment]
Looks like Reda updated the `README` when we bumped to `1.7.1`; sorry for not catching that for `1.7`.
