### ISSUE TITLE
Dsiable specific warning?

### ISSUE THREAD

**Issue by ahite-archermalmo** [thoughtbot/neat#295]
Is there a way to disable a specific warning?

I'm adding Neat to an existing project that is using "breakpoint" which Neat used to use, but now uses "media". I'd like to disable that specific warning and not all warnings globally.

**Comment by kaishin** [comment]
There is no support for feature-specific warning settings and no plans to add it. 

Out of curiosity, would it be hard to do a global search and replace in your case?

**Comment by ahite-archermalmo** [comment]
yeah, i guess. i just didn't want to mess with the other developers code too much.
