### ISSUE TITLE
span rows

### ISSUE THREAD

**Issue by digitalvapor** [thoughtbot/neat#297]
What is the Neat-esque way to "span rows" or create a single grid item that is 100% webpage height excluding headers and footers. When I say 100%, I don't just mean viewport height, but spanning the *entire* webpage height.

I was just looking for a pure CSS / non-javascript method. I can provide drawings of what I mean if you wish. I realize that the typical nesting design of Neat is more span-column oriented, but had to ask.

Cheers, love Bourbon/Neat.

**Comment by kaishin** [comment]
There is no Neat-esque way to do that, but you can use table display for that item and the item containing the rows using [display-context](http://thoughtbot.github.io/neat-docs/latest/#display-context)

**Comment by digitalvapor** [comment]
That's what I thought, thanks! I just changed my nested structure to make it happen.
