### ISSUE TITLE
1.5.1 causes Sass segmentation fault

### ISSUE THREAD

**Issue by svileng** [thoughtbot/neat#298]
I installed `1.5.1` via bower and I'm using the latest `gulp-sass` (which uses `node-sass 2.0.0-beta`). The message I got straight after `@import`-ing Neat was

```
[14:08:18] Starting 'sass'...
[1]    88062 segmentation fault  gulp
```

Reverting to `1.5.0` fixed the problem.

**Comment by mistergraphx** [comment]
:+1:  thx exactly the same problem

**Comment by whmii** [comment]
Not sure if Neat supports lib-sass. @wardpenney do you have any context on this. otherwise I can spin up a node server today and test this out.

**Comment by tysongach** [comment]
We started officially supporting LibSass with [Neat in v1.7.0](https://github.com/thoughtbot/neat/releases).

**Comment by wardpenney** [comment]
Yeah, since this is an older version that didn't officially support libsass, I don't think it needs to be addressed. Thanks for the issue though!

**Comment by svileng** [comment]
@tysongach @wardpenney Do you think there would be any problems using Neat `1.7.0` on top of Bourbon `3.2.4`?

**Comment by wardpenney** [comment]
@svileng I don't think it would be a problem.
