### ISSUE TITLE
omega applying clear to wrong element

### ISSUE THREAD

**Issue by journalbits** [thoughtbot/neat#300]
I'm making a grid that fits in a 12-column section. I want 2 sections, each of 6 columns width, and there will be multiple rows. I have something very similar working on one page (except that it's 4 sections each of 3 columns) but for some reason on this page the wrong element seems to be having `clear: left;` applied to it when it should instead have `margin-right: 0;`.

Here's a screenshot of the problem visually.

![screen shot 2015-01-24 at 11 31 30](https://cloud.githubusercontent.com/assets/7951554/5886377/90eab7e4-a3bd-11e4-9d8a-05b396465316.png)

And here are screenshots showing that the elements have `clear: left;` and `margin-right: 0;` seemingly applied to the wrong elements.

![screen shot 2015-01-24 at 11 34 07](https://cloud.githubusercontent.com/assets/7951554/5886376/909a6096-a3bd-11e4-817e-a9f61d6774cf.png)

----

![screen shot 2015-01-24 at 11 34 18](https://cloud.githubusercontent.com/assets/7951554/5886378/914dfde0-a3bd-11e4-81d8-bb956467c6d4.png)

This is the markup that's being generated:

    <section class='day_container'>
      <div class='day-info-container'>
        ...
      </div>
      <div class='daily-data-container'>
        ...
      </div>
      <div class='daily-data-container'>
        ...
      </div>
      <div class='daily-data-container'>
        ...
      </div>
    </section>

and here's the relevant section of my stylesheet:

    .day_container {
      @include outer-container;
      margin-top: 10px;

      div.daily-data-container {
        text-align: left;
        padding: 15px;
        margin-top: 5px;
        margin-bottom: 5px;
        border: 1px solid #000;
        border-radius: 10px;

        @include media($desktop) {
          @include span-columns(6);
          @include omega(2n);
        }

        @include media($tablet) {
          @include span-columns(4);
          @include omega(2n);
        }

        @include media($mobile) {
          @include span-columns(4);
          @include omega(n);
        }

        &:hover {
          border-color: #d0d0d0;
        }
      }
    }

The screenshots come from using the `$desktop` size screen (defined as `min-width: 801px;`).

Any ideas as to what I'm doing wrong?

**Comment by joshuaogle** [comment]
Hi @journalbits,
It's because of the `.day-info-container` element. Because it is in the same container as the `.daily-data-container` elements, it's still counting as a child. So when `omega()` is using the `2n` counter, it's counting the info-container as well and clearing the 2nd element in the container, which is the first `data-container` element. Hopefully that makes sense.

Since you seem to only be floating the data-containers, I would recommend wrapping them all in their own container. That should solve the problem.

**Comment by journalbits** [comment]
Thanks @joshuaogle, makes a lot more sense now.
