### ISSUE TITLE
Install directory

### ISSUE THREAD

**Issue by DenBeke** [thoughtbot/neat#303]
If I install Bourbon, I can use custom install directory:

    $ bourbon install --path my/dir

This doesn't seem to work for Neat... Am I doing something wrong, or is that function missing?

**Comment by joshuaogle** [comment]
It's just missing from Neat. You don't need it when using the Ruby gem or an NPM module, so it's not too surprising. Adding the option the same as it is in Bourbon should be pretty easy to implement though.

**Comment by DenBeke** [comment]
Ok, thank you...
Simple unix `mv` command also works :)
