### ISSUE TITLE
Column Ordering or Content Folding

### ISSUE THREAD

**Issue by toobulkeh** [thoughtbot/neat#304]
I'd love to implement something that TWBS has in it's mobile-first design into Bourbon Neat:
http://getbootstrap.com/css/#grid-column-ordering

```html
<div class="row">
  <div class="col-md-9 col-md-push-3">.col-md-9 .col-md-push-3</div>
  <div class="col-md-3 col-md-pull-9">.col-md-3 .col-md-pull-9</div>
</div>
```
While The HTML mockup is nasty, the idea is valuable for handling reordering content.

Here's the CSS strategy that this compiles into:
```sass
@mixin make-sm-column-offset($columns) {
  @media (min-width: $screen-sm-min) {
    margin-left: percentage(($columns / $grid-columns));
  }
}
@mixin make-sm-column-push($columns) {
  @media (min-width: $screen-sm-min) {
    left: percentage(($columns / $grid-columns));
  }
}
@mixin make-sm-column-pull($columns) {
  @media (min-width: $screen-sm-min) {
    right: percentage(($columns / $grid-columns));
  }
}
```

Here's a much more complex approach and example, which I will ignore for now, but call related as food-for-thought:
http://css-tricks.com/content-folding/

The poor man's fix to this is duplicating content and hiding/showing each on different sizes, which I've also found the need to steal from TWBS in a Bourbon project, so I've opened this discussion on the topic:
thoughtbot/bourbon/issues/656

I'd be happy to submit a PR to tackle this challenge, just would like to discuss various strategies before I start down a single path and make sure that it would be a welcome addition to neat.

**Comment by toobulkeh** [comment]
I've found the mixins `row` and `direction-context` but I'm not sure how to use them properly, or if these are doing what I'm expecting. Any ideas?

**Comment by toobulkeh** [comment]
So after much struggles, I found that neither of these solutions really helped for a mobile/responsive design.

I ended up just duplicating the content (columns) and showing/hiding based on layouts.

If anyone has a better method, I'm all ears.

**Comment by ivanjuras** [comment]
I'd like to know the solution for this as well.

**Comment by wardpenney** [comment]
@toobulkeh @ivanjuras had a similar question in #313. Have you tried `shift`? You would arrange the markup in the desired way for mobile, then have breakpoints that define grid and shift the elements to reorder.

While reordering is effective, content folding is not possible yet. Flexbox can do complex reordering, but folding is a different problem. Chris at css-tricks.com has [a good article](https://css-tricks.com/content-folding/) describing attempt to fold with css regions, but browser support is not great.

**Comment by jonnykates** [comment]
I managed to find a work-around for this, at least for two columns.

In my HTML I ordered the column divs in the order that I want them to appear *after* the breakpoint. 

```
<div class="container">
  <div class="four-cols">
    I want this div to be on the right normally, but then sit on top when the columns go full width after breakpoint
  </div>
  <div class="eight-cols">
    This div is the main column and needs to sit on the left normally, but fold underneath after break
  </div>
</div>
```

Then I floated them in my SCSS to force the order I want them to appear in *before* the breakpoint. You have to include Neat's omega mixin here to sort out the gutters as you're using floats to botch up the column ordering that Neat expects.

```
.four-cols {
  @include span-columns(4);
  float: right;
  @include omega;
}
.eight-cols {
  @include span-columns(8);
  float: left;
}
```

Then my Neat media query sets both divs to fill-parent(). At this point, Neat respects the order of the divs as they appear in the DOM, and so the column you've floated right, now appears on top of the other.

```
.container div {
  @include media(max-width 400px) {
    @include fill-parent();
  }
}
```

**Comment by smargh** [comment]
If I understand the intention, then this Pen ought to demonstrate the basic way to use `direction-context` in order to have a mobile "footer" element appear on the left-hand side, inline with the main content in desktop: http://codepen.io/smargh/pen/NPEwzR

**Comment by cr0ss** [comment]
Direction content doesn't solve such a task as I understand it:
aside (left)
aside (right)
content

where it should look like [ aside(left) - content - aside(right) ]

PS: codepen example is 404.

**Comment by whmii** [comment]
We will work on making updates to the content reordering. Most of what is needed here can be accomplished with `shift` but some custom code may be necessary.

Closing for now.
