### ISSUE TITLE
Error: Incompatible units: 'em' and ' ' 

### ISSUE THREAD

**Issue by Antonranestam** [thoughtbot/neat#306]
Getting modular scale error on my latest update of Bourbon and Neat. 

Message: 

Error: Incompatible units: 'em' and ''.
        on line 37 of assets/bourbon/dist/functions/_modular-scale.scss
        from line 6 of assets/neat/app/assets/stylesheets/_neat-helpers.scss
        from line 7 of assets/neat/app/assets/stylesheets/_neat.scss
        from line 9 of sass/main.scss

Would be great with some pointers. 
Tried stripping main.scss and only importing bourbon & neat, still getting error.

**Comment by tysongach** [comment]
What version of Bourbon and Neat are you using?

**Comment by Antonranestam** [comment]
Bourbon 4.1.1 
Neat: 1.7.1

**Comment by wardpenney** [comment]
@Antonranestam possible problems:

* Did you happen to set a variable named `$golden` before Neat is loaded?
* Did you make sure you are `@import`-ing Bourbon before Neat?

**Comment by Antonranestam** [comment]
Fixed it. 
Problem was Neat-helpers was imported before Neat. Seems to be working good now! :)
