### ISSUE TITLE
block-collapse and a container containing single element

### ISSUE THREAD

**Issue by esad** [thoughtbot/neat#308]
I have this simple piece of HTML:

![screen shot 2015-02-04 at 23 49 50](https://cloud.githubusercontent.com/assets/11807/6051473/a7768dda-acc8-11e4-8108-09f2248ff2b7.png)

with following CSS:

```css
.content { @include outer-container(); }
h1 { @include shift(1); @include span-columns(5, block-collapse); }
```

What I want to achieve is this:

![screen shot 2015-02-04 at 23 49 36](https://cloud.githubusercontent.com/assets/11807/6051474/a778bc22-acc8-11e4-862a-8785fad00ac6.png)

However https://github.com/thoughtbot/neat/blob/master/app/assets/stylesheets/grid/_span-columns.scss#L82 seems to kick in and decrease the width back.

Adding a simple dummy div after h1 to avoid trigger `last-child` rule works, but how could this be fixed in a more idiomatic way?

**Comment by wardpenney** [comment]
@esad I think this is intended to mimic the behavior for the last column of the grid, similar to `display: block`. For this particular case, it is not helpful. However, the grid is set up with `last-child` removal of the margin in mind. While that is the paradigm, it would be weird to break it.

However, there could be an override parameter that is possible. Like a `not-omega` flag you can pass-in. That may just clutter things up, though.
