### ISSUE TITLE
Weird issue with @include outer-container

### ISSUE THREAD

**Issue by Chrisedmo** [thoughtbot/neat#312]
In my scss, I have:

    .container {
	@include outer-container;
    }

Which compiles to:

    .container {
        content: "";
        display: table;
        max-width: 68em;
        margin-left: auto;
        margin-right: auto; 
    }

The display table is breaking the max width, and collapsing all my items. + there should be no generated content on the main selector? Any ideas, what's going on?

**Comment by whmii** [comment]
That's weird, this should have an `&:after…`on it. Let me take a look at the code base and see what the intended result is.

**Comment by whmii** [comment]
All that happens in `outer-container` is an `@import  clearfix` and the `max-width` etc. See  https://github.com/thoughtbot/neat/blob/master/app/assets/stylesheets/grid/_outer-container.scss#L31

The clearfix mixin is what supplies the `content` and `display: table` which should be within a `&::after` psudo-element. See
https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/addons/_clearfix.scss

I would check your Neat and bourbon versions to make sure they are up to date with the current release. If this doesn't solve your issue please post a bit of information about the project including what stack/build tools you are using and what versions of Neat and Bourbon you are running.

**Comment by beckyconning** [comment]
given this is all outer-container does should it be used more than once per page? what is the recommended use of outer-container?

**Comment by whmii** [comment]
I wouldn't feel like there is a recommended use. you could use it to say 'this is my main container' or just do define a row. it would depend on what your layout was.

**Comment by wardpenney** [comment]
IMO, I wouldn't define more than one outer container per node tree. If you needed a row-like split for responsive stacking, just use a `@clearfix` on your row element. Thanks for looking into it @whmii!

**Comment by nickcotton** [comment]
FWIW, I'm also seeing this issue.

Neat version 1.7.2 and bourbon 4.2.2.

Compiling with gulp-sass v1.3.3.

The problem isn't limited to `outer-container` though. This happens everywhere I use the `clearfix` mixin.

**Comment by nickcotton** [comment]
Ahh ok, I think I've discovered the cause. I'm making a wordpress theme based on underscores.me. This contains a `clearfix` mixin of its own, which overrides bourbon's. Removing said mixin solves the problem.

Hopefully this helps anyone else running into this. It's a pretty specific set of circumstances.

**Comment by Chrisedmo** [comment]
Ahhh that's what was happening to me too!! I didn't realise that. Good spot.

Chris

**Comment by tameroski** [comment]
Also fixed for me. Thanks @nickcotton for figuring it out.
