### ISSUE TITLE
[CLI] Displaying the installed version via a flag

### ISSUE THREAD

**Issue by themccallister** [thoughtbot/neat#315]
Running the command `neat -v` does not display the neat version number. I can run the same commands on bourbon and bitters to determine my version.

![screen shot 2015-02-14 at 10 09 29 am](https://cloud.githubusercontent.com/assets/5354908/6200543/b1043ae4-b431-11e4-9c9d-29d6ef662855.png)

**Comment by wardpenney** [comment]
It looks like the `require` statement in the gemspec is pointing to the wrong path for the `version` file. Want to fix it up and make a PR @themccallister, or I can?
