### ISSUE TITLE
Neat Documentation Links to thoughtbot Brand Guidelines

### ISSUE THREAD

**Issue by chuise** [thoughtbot/neat#316]
If you click on the Neat logo on http://thoughtbot.github.io/neat-docs/latest/ it takes you to http://thoughtbot.github.io/.

![neat-docs-link](https://cloud.githubusercontent.com/assets/124926/6269551/05562e7e-b822-11e4-98ca-8061288037ed.gif)

**Comment by wardpenney** [comment]
Yep they're just linking to root. I'll look into how Sass doc makes that link when I get a moment. If you see the point, feel free to make a PR. Thanks!

**Comment by mehlah** [comment]
Looks like it's fixed, thanks to https://github.com/thoughtbot/neat-docs/commit/052f77adddaebc921734270635edfe50a5d43f90
