### ISSUE TITLE
Add ability to set a contextual gutter

### ISSUE THREAD

**Issue by ChezFre** [thoughtbot/neat#317]
I have a website which uses the default settings for columns and gutters. But one block on my site is a grid of 8 | 4, where I don't need any gutters and the columns need to have the exact same width because there's a responsive image that defines the height.

The 8 column grid is again divided in two times 4 of 8 that need to have the same height again. This way I get a grid of 8 squares in which I can group an image (blue squares) with a description (grey blurred squares)

![example](https://cloud.githubusercontent.com/assets/442020/6287724/1003cf28-b914-11e4-812b-4fe9fc4ba890.gif)

Because of the default gutter however, the columns are never the same width. Setting block-collapse on span-colums removes the spaces, but adds the margin to the column, which makes the width of my columns different and prevents the images from lining up correctly.

If I were able to define a gutter within a certain context this wouldn't be a problem.

**Comment by wardpenney** [comment]
This is interesting @ChezFre, I need to delve into it a bit more to understand the example. Is it possible for you to make a repo setting up the example? If not, I will give it a shot to re-create the situation next week when I have a minute.

**Comment by ChezFre** [comment]
Hi @wardpenney, thank you for your time and input. I've set up an example of what I'm trying to achieve at https://github.com/ChezFre/neat-example.

The problem is resolved when I set the $gutter to 0. However, since this part of the site is an exception it would be undesirable to do so. At the moment I've just abandoned the use of the grid for this particular block.

**Comment by xpepermint** [comment]
+1

**Comment by whmii** [comment]
We will be adding support for custom grid sections.

**Comment by whmii** [comment]
However, support for this will ont be present in any 1.X version.
