### ISSUE TITLE
No changes reaction on grid_settings

### ISSUE THREAD

**Issue by DryamDryam** [thoughtbot/neat#319]
Hello!
When y trying change column or gutter or more settings on grid_settings, it doesn't react to it in any way, but when i change grid-columns or max width - it's work! What do I do not so?

$column: 211px !default;
$gutter: 20px !default;
$grid-columns: 6;
$max-width: em(1366);

Thank you!

**Comment by ksesong** [comment]
I have the same issue (node-neat package: 1.7.1beta), and I can't figure out why. I have tried to change the default values directly at the source, but nothing happens.

**Comment by tysongach** [comment]
@DryamDryam @ksesong What’s the structure of your project (Sass imports, etc) and where are you defining these grid settings?

**Comment by ksesong** [comment]
Here is the content of the main stylesheet:
```scss
// == Importing modules
@import 'bourbon';
@import 'neat';

// == Helpers
@import 'helpers/_normalize';
@import 'helpers/_reset';
@import 'helpers/_variables';  // <== Grid settings are set here
@import 'helpers/_mixins';
@import 'helpers/_media-queries';

// == Layout, components...
```

With grid settings as such:
```scss
$column: em(40);
$gutter: em(20);
$grid-columns: 14;
$max-width: em(1100);
$visual-grid: true;
```

This is especially strange as both the `$grid-columns` and `$max-width` variables are operational. My `libsass` version is `3.1.0`, which shouldn't be an issue with this version.

**Comment by tysongach** [comment]
@ksesong As described in Neat’s [readme](https://github.com/thoughtbot/neat#using-neat), you need to import your grid setting changes _before_ `neat`. So, something like this:

```scss
@import 'bourbon';
@import 'grid-settings';
@import 'neat';
```
