### ISSUE TITLE
Error: Incompatible units: 'em' and ''

### ISSUE THREAD

**Issue by wnordmann** [thoughtbot/neat#324]
I am getting the following error with neat 1.7.2 and Bourbon 4.0.2 and I am building with grunt sass.

__Error: Incompatible units: 'em' and ''.
        on line 37 of {path}/lib/bourbon/functions/_modular-scale.scss
        from line 6 of {path}/lib/neat/_neat-helpers.scss
        from line 3 of {path}/scss/_vars.scss
        from line 2 of {path}/scss/app.scss
  Use --trace for backtrace.__

When I use neat 1.7.0 I don't get an error.

**Comment by tysongach** [comment]
Please see this [related issue](https://github.com/thoughtbot/neat/issues/306) and see if it solves your issue.

You also may want to update Bourbon. It’s up to [4.2.1](https://github.com/thoughtbot/bourbon/releases) now.

**Comment by wnordmann** [comment]
I saw that related issue and that didn't seem to be the problem.  I think
my problem might be some conflict between the ruby gems and bower.  I'll
get work on getting more details.

**Comment by leonprou** [comment]
The update to newer version of bourbon fixed my issue.

If you don't want to update, you can just update the modular-scalar version of bourbon to a newer one.  I download it from bower and replaced the bourbon version with my own.

**Comment by wnordmann** [comment]
I was related to the order of loading the libraries.  Everything works now.

**Comment by asselstine** [comment]
@tysongach Solved my issue as well.  Thanks.
