### ISSUE TITLE
Undefined mixin 'display'  using cards component.  Fails locally and on heroku.

### ISSUE THREAD

**Issue by elmo** [thoughtbot/neat#332]
Sass::SyntaxError: Undefined mixin 'display'.

This occurs on my local environment and when deploying to heroku.  I've gone through the troubleshooting steps, with no success.

**Comment by wardpenney** [comment]
@elmo I think you mean you are using the [.card pattern](https://github.com/thoughtbot/refills/blob/master/source/stylesheets/refills/_cards.scss) from Refills? The [display mixin](https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/css3/_flex-box.scss) is in Bourbon, so you will need to have that included prior to calling it. Let me know if that solves it and we can close this. Thanks.
