### ISSUE TITLE
Deprecation warnings  Passing 100%, a non-string value, to unquote() from when deploying to heroku.

### ISSUE THREAD

**Issue by elmo** [thoughtbot/neat#333]
DEPRECATION WARNING: Passing 100%, a non-string value, to unquote()
       will be an error in future versions of Sass.
       on line 27 of /tmp/build_9267e583e31fc2d70dd66ebd798e28ab/vendor/bundle/ruby/2.1.0/gems/bourbon-3.1.8/app/assets/stylesheets/helpers/_deprecated-webkit-gradient.scss, in `linear-gradient'
       from line 73 of /tmp/build_9267e583e31fc2d70dd66ebd798e28ab/vendor/bundle/ruby/2.1.0/gems/bourbon-3.1.8/app/assets/stylesheets/addons/_button.scss, in `simple'
       from line 26 of /tmp/build_9267e583e31fc2d70dd66ebd798e28ab/vendor/bundle/ruby/2.1.0/gems/bourbon-3.1.8/app/assets/stylesheets/addons/_button.scss, in `button'
       from line 2 of /tmp/build_9267e583e31fc2d70dd66ebd798e28ab/app/assets/stylesheets/bitters/extends/_button.scss
       from line 1 of /tmp/build_9267e583e31fc2d70dd66ebd798e28ab/app/assets/stylesheets/bitters/extends/_extends.scss
       from line 10 of /tmp/build_9267e583e31fc2d70dd66ebd798e28ab/app/assets/stylesheets/bitters/_bitters.scss
       from line 17 of /tmp/build_9267e583e31fc2d70dd66ebd798e28ab/app/assets/stylesheets/application.css.scss
       DEPRECATION WARNING: Passing 100%, a non-string value, to unquote()

**Comment by wardpenney** [comment]
Good find

**Comment by whmii** [comment]
This is infact an issue with the [Bourbon](http://bourbon.io)'s `button()` mixin (which is getting deprecated anyway) and not actually an issue with neat.
