### ISSUE TITLE
omega(3n+1) evaluates to :nth-child(4n) in css

### ISSUE THREAD

**Issue by ZeroMax-dev** [thoughtbot/neat#334]
I want to take a certain element in my grid out of the layout (e.g. with position:absolute) with the html staying the same. For that I need to add an offset to the omega-mixin so that the following elements are still treated correctly. The omega-mixin however does not regard the offset value correctly.

	.option {
		@include omega(3n+1);
	}

translates to:

	.option:nth-child(4n) {
		margin-right: 0;
	}

	.option:nth-child(4n+1) {
		clear: left;
	}

in css, but should be:

	.option:nth-child(3n+1) {
		margin-right: 0;
	}

	.option:nth-child(3n+2) {
		clear: left;
	}

I am using neat 1.7.1

**Comment by wardpenney** [comment]
Yep that looks bugged. Omega also sets the clear so watch out if you're using it to do some absolute placement. You may want to do that just using your own nth-child.

**Comment by wardpenney** [comment]
Could be fixed together with #318

**Comment by joshuaogle** [comment]
Added a possible fix in #340, if you would like to take a look.

**Comment by jonnykates** [comment]
+1

**Comment by whmii** [comment]
Seems like this has been fixed.

closing for now
