### ISSUE TITLE
gulp-sass returns error when specifying $gutter in pixels

### ISSUE THREAD

**Issue by MrPaulDriver** [thoughtbot/neat#336]
I am following along with the readme to get the hang of everything but I am having some difficulty specifying $gutter in pixels although I can specify an 'em' value or something like 'em(30px)'.

When specifying gutter width in pixels gulp-sass returns the following error...

[gulp-sass] cannot add or subtract numbers with incompatible units on line 9 in /pathto/neat/app/assets/stylesheets/functions/_private.scss

I am not sure if this is a gulp-sass issue or perhaps an indication that Neat may have some incompatibility with gulp-sass. I think that line 9 in _private.scss refers to linting but apart from this I don't know what is going on.

Thank you.

**Comment by sebastianromero** [comment]
I solved it asigning the gutter value using the modular scale function.
For example:
```sass
 $gutter: modular-scale(2, 2em, $golden);

**Comment by stephensauceda** [comment]
Have you defined `$column` as a pixel value as well? Per the docs for the `$gutter` variable:
> The unit used should be the same one used to define $column.

By default, `$column` and `$gutter` use the `modular-scale` function which returns an em value. So if specifying `$gutter` in pixels, you must do the same with `$column`.

**Comment by tysongach** [comment]
:point_up: What @stephensauceda said…

Does doing that resolve your issue?
