### ISSUE TITLE
Undefined mixin 'box-sizing'

### ISSUE THREAD

**Issue by sunilw** [thoughtbot/neat#342]
I've started a new static html project.
In the sass directory I've installed neat using the command 'neat install.

In the first line of "site.sass" I've got "@import "neat/neat".

I've got a gruntfile that watches for changes in the sass directory and uses grunt-contrib-sass to compile.
If I run 'grunt sass' the task runs.

Presently when I run 'grunt sass' I get the following fatal error:

`Running "sass:dist" (sass) task
Error: Undefined mixin 'box-sizing'.
        on line 3 of sass/neat/grid/_grid.scss, in `box-sizing'
        from line 3 of sass/neat/grid/_grid.scss
        from line 11 of sass/neat/_neat.scss
        from line 2 of sass/site.sass
  Use --trace for backtrace.`

It looks like the 'box-sizing' mixin isn't being found.
How do I make make sure that the mixing gets found?

**Comment by tysongach** [comment]
The `box-sizing` mixin is part of Bourbon. Do you have Bourbon installed in your project and are you importing it before Neat?

**Comment by tysongach** [comment]
Closing due to no response.
