### ISSUE TITLE
Config setting to limit span-columns() parameter to integer

### ISSUE THREAD

**Issue by markpalfreeman** [thoughtbot/neat#344]
I understand that `@span-columns` should allow for decimal parameters if someone wants to create a layout that is not evenly multiplied into `$grid-columns` (i.e. 5-columns inside a 12-column grid).

However, for team code consistency, it would be helpful to set something like a `$strict-grid` boolean that, if `true`, would limit the parameter to an **integer** in order to always align columns to the `$grid-column` grid widths. 

Then, if developers were attempting to fudge layouts without knowing decimal implications, they could be warned to adjust to an integer.

Has this been considered?

**Comment by whmii** [comment]
Currently there are no plans to add this feature, however Neat is currently a little too agnostic about what you can throw in a mixin and get away with it.

This decimal configuration is something we would likely remove in future versions.
