### ISSUE TITLE
Make `$column` and `$gutter` not use `modular-scale`

### ISSUE THREAD

**Issue by kylefiedler** [thoughtbot/neat#346]
The `modular-scale` functions are just complicating what is essentially a 3 to 1 ratio. Adding the function is unnecessarily complicating the code.

```scss
$column: 3em !default;
$gutter: 1em !default;
```

**Comment by tysongach** [comment]
:+1: There’s been chatter about decoupling Bourbon from Neat. There’s only a few small functions and mixins from Bourbon that Neat uses, all them are non-essential ([related PR](https://github.com/thoughtbot/neat/pull/327)). Removing `modular-scale` would be trivial.

**Comment by kennethormandy** [comment]
Really like this idea, and I’d be interested in helping. I was maintaining [Straight Up](https://github.com/kennethormandy/straight-up/), which was Neat without Bourbon, and it worked quite well. It’s nice to avoid the extra dependency if you’re using Autoprefixer.
