### ISSUE TITLE
block-collapse option causes stuttering rendering

### ISSUE THREAD

**Issue by smargh** [thoughtbot/neat#348]
When passing the `block-collapse` option to `span-columns`, my website stutters when rendering the page. The element will appear at the original width (i.e. what the width would be if no `$display` option were passed), then it will quickly expand to the actual width I want (width + gutter). 

If I remove the `block-collapse` option, the element has the gutter + width layout one would anticipate, and there is no stuttering at all. Add `block-collapse` option, and the stuttering appears.

Solution?

**Comment by whmii** [comment]
I checked this out and oddly enough I wasn't able to recreate it. I'm going to close this issue for now but If it is still a problem it would be great to know what browser you are using, as it sounds like the browser is having a difficult time rendering the overrides.
