### ISSUE TITLE
Support fluid layout?

### ISSUE THREAD

**Issue by krzkrzkrz** [thoughtbot/neat#349]
Been skimming through the docs for a fluid layout. As in not fixed width. Anyone know how this can be achieved?

**Comment by joshuaogle** [comment]
Neat is a fluid grid by default, you just need to make sure its container is using `max-width` instead of `width`. If it isn't resizing it's probably a parent element that is set to a specific width. The [demo page](http://neat.bourbon.io/examples) is a good example of how to set things up.

**Comment by tysongach** [comment]
Closing due to lack of response.

**Comment by krzkrzkrz** [comment]
@joshuaogle It is fluid to based on a fixed grid. The example link has a fixed grid (12 columns). The columns are not fluid. Fixed at full width of 1024px.

Correct me if I am wrong.

**Comment by joshuaogle** [comment]
@krzkrzkrz There is an `outer-container` that can be set to a set width, but you don't need to use it. The columns and margins are all percentage based, so it works great without a container too. I think a fully fluid example in the docs would be a great idea.

**Comment by krzkrzkrz** [comment]
Hmmm that would be nice to have

**Comment by wardpenney** [comment]
You can just make a custom class and all it has is a `@include clearfix;` That should give you a row concept.
