### ISSUE TITLE
Create functions to only return property values

### ISSUE THREAD

**Issue by VaclovasV** [thoughtbot/neat#350]
Hello,
We are using neat system and we like it, because it is easy, but, there are some issues with it, compared with other grid systems, for example: susy.
Every time, then you want to redeclare column width, you have to use span-columns() include and already added properties like float, display block, margins will be added:
http://prntscr.com/779785

1. Why display block is added with span-columns include? Float converts item to block anyway.
Read more, here: http://stackoverflow.com/questions/6372021/redundant-css-rules-ie-float-displayblock
Maybe this can be configured from neat config?

2. Adding functions to neat, to return just a width of columns, would be great, because now I have to override columns width like this and I'm not even sure if this will be supported with next Neat version, because it's unofficial:

```scss
width: flex-grid(7) + flex-gutter();
```

If I will use span columns, include will make code too redundant width floats, display blocks and etc. This will be nightmare for someone to inspect and additional KB's to load for end user.

It would be awesome, to make these improvements.

Thank you!

**Comment by j-walker23** [comment]
@VaclovasV I am just looking into this. You like it pretty well?

Also to make sure I understand, is `flex-grid` your custom function names? If so are you using `flexbox` with this? If so how does that work?

**Comment by VaclovasV** [comment]
flex-grid is an non documented, internal neat function, which returns width of grid column, it has nothing to do with flexbox :)
You can find it here:
https://github.com/thoughtbot/neat/blob/2875ee28b844e6a4bb3506b909661d9d3a484a82/app/assets/stylesheets/grid/_private.scss
Why it's private? Why people can't get just width of column width?
It would be great, to make them public and make other dimmension as returnable with functions.

**Comment by j-walker23** [comment]
ahh gotcha, thanks for the info i appreciate it!

I will be starting a app soon and i am looking to shake up my frameworks. Would you recommend this?

**Comment by VaclovasV** [comment]
You can choose between susy and neat, you will win in both ways :)
Susy is more advanced, you can have every dimmension returned with function and use it in every css property. Neat is more limited, but it is easier and compiles faster, stacks with bourbon. Compilation time is not a factor, then you are using libsass.
We have a boilerplate, where you can try neat (spriting and some other features are included too):
https://github.com/devbridge/Front-End-Toolkit

**Comment by j-walker23** [comment]
That is awesome, thank you!

**Comment by Diope** [comment]
Months later, I must thank you for FET!

**Comment by whmii** [comment]
Glad you found those functions useful. For the current version it is fine to use those undocumented internal functions as the code base is quite stable.

Great solution, closing for now.
