### ISSUE TITLE
[CLI] Option to specify a directory path

### ISSUE THREAD

**Issue by giorgiofellipe** [thoughtbot/neat#351]
I was wondering why there is not possible to specify a directory to install neat, same as possible on bourbon?

**Comment by tysongach** [comment]
Currently, no…but it’s a bummer that we aren’t being consistent with that, so we should really add this to Neat’s CLI.

Thanks for the heads up!

**Comment by mehlah** [comment]
@tysongach I've just added the support for a `--path` option to Neat's CLI at https://github.com/craftsmen/neat/commit/86256e037b1a98f514008a5230095e7d108f89b6
I can PR it as soon as #329 got merged, which makes Neat's CLI based on Thor.

**Comment by bostonaholic** [comment]
:+1:

**Comment by sobolevn** [comment]
It is still not working:

    MacBook:winste sobolev$ neat install --path=scss
    Neat files installed to neat/

**Comment by whmii** [comment]
@mehlah Sorry for the delay. Still in to making a PR for this?

**Comment by mehlah** [comment]
@whmii PR #459 opened 👍

**Comment by whmii** [comment]
sweet 🍬
