### ISSUE TITLE
Use via bower example pls

### ISSUE THREAD

**Issue by landed1** [thoughtbot/neat#352]
I I install using bower then the directory pattern changes and then one is forced to install like this

@import "../../node_modules/node-bourbon/node_modules/bourbon/app/assets/stylesheets/bourbon";
@import "../../bower_components/neat/app/assets/stylesheets/neat";

You can see above that bourbon is via npm (node).
I am wondering if this (my N E A T install via bower) is going to work then with all the imports as it seems to add very little css to my generated file...

**Comment by qburns** [comment]
Not sure if you still need help with this, but the way importing with Bourbon works is it only pulls in the parts of the code it needs.

Try adding something like 

body {
@include background(linear-gradient(red, green) left repeat);
}

and see if your generated CSS is properly importing the styles from bourbon

**Comment by landed1** [comment]
Thanks for your help - I figured it out already however. Bourbon doesn't itself generate any css like Bootstrap does and coming from that way I was expecting css ! 
It starts to create the css as you use the mixins like you show then css can be seen.
