### ISSUE TITLE
Obsolete warning concerning the box-sizing mixin?

### ISSUE THREAD

**Issue by raphaellarrinaga** [thoughtbot/neat#354]
That warning is showing when compiling using neat (1.7.2) and bourbon (4.2.3).

        WARNING: The box-sizing mixin is deprecated and will be removed in the next major version release. This property can now be used un-prefixed.
	on line 410 of node_modules/node-neat/node_modules/node-bourbon/node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecated-upcoming.scss
	from line 3 of node_modules/node-neat/assets/stylesheets/grid/_box-sizing.scss
	
But I see [in the logs](https://github.com/thoughtbot/neat/releases/tag/v1.7.2) that prefixes have been removed.

Is this warning obsolete? Or maybe this is shown because of the box-sizing mixin in

    node_modules/node-neat/assets/stylesheets/grid/_box-sizing.scss

Anyway, is it possible to hide warnings to stop polluting the logs?
I am compiling with grunt.

Note that this is related to these two issues:
 
- <https://github.com/thoughtbot/neat/issues/342>
- <https://github.com/thoughtbot/neat/issues/322>

**Comment by mehlah** [comment]
There should be no warning in v1.7.2 as Neat doesn't use the deprecated Bourbon's mixin.
The line mentionned by the warning doesn't use a mixin https://github.com/thoughtbot/neat/blob/v1.7.2/app/assets/stylesheets/grid/_box-sizing.scss

Are you still experiencing this? Sure that you are loading Neat 1.7.2?

**Comment by tysongach** [comment]
Any update?

Have you tried toggling Neat’s [`$disable-warnings`](http://thoughtbot.github.io/neat-docs/latest/#disable-warnings) variable to `true`?

**Comment by raphaellarrinaga** [comment]
Hi,
Indeed, I was using v1.7.0. The warning does not show anymore after updating to v1.7.2.
I was compiling with grunt using old modules versions installed from a package.json file I took from a previous project. Bad idea.

@tysongach The message was still showing after setting $disable-warnings to true.
Anyway that's fixed, thanks.
