### ISSUE TITLE
Pad mixin returns same percentage regardless of context

### ISSUE THREAD

**Issue by CGTS** [thoughtbot/neat#356]
I don't know if I'm doing something wrong but, when using the `@include pad(0 default);` mixin in a nested grid it returns the same percentage as the parent container resulting in less spacing. 

My assumption was that the default padding would be equal to the gutter size defined in the grid settings. I know grid margins adjusts based on whether or not they are nested. Is the pad mixin supposed to work the same way or am I mistaken?

**Comment by qburns** [comment]
Try using padding: flex-gutter(); to generate the same padding as the gutter.

**Comment by CGTS** [comment]
Thanks.
