### ISSUE TITLE
Undefined variable golden

### ISSUE THREAD

**Issue by shingletondotorg** [thoughtbot/neat#360]
When I @import 'neat-helpers'; I get an Undefined variable: "$golden". error.

Any advice on how to resolve this.

I tried adding $golden: 1.6180339887 to application.css.scss but did not work

Thanks

**Comment by wardpenney** [comment]
That is because it is a variable defined in Bourbon. Neat is still dependent on Bourbon, so you will have to `@import 'bourbon'` before this line.

**Comment by malomalo** [comment]
Having the same issue, bug introduced in Neat v1.7.2, Bourbon is required before Neat.

Neat 1.7.1 is good to go.

I hope they change the variable name to something less broad than $golden

**Comment by shingletondotorg** [comment]
Thanks!
