### ISSUE TITLE
Flex Question

### ISSUE THREAD

**Issue by joelcoxokc** [thoughtbot/neat#367]
Hello Neat Team, I am Working on the Aurelia-Interface, and I am leveraging Flex-box in many ways. However, Id'e like it to be a standard with syntax, similar to your table layout. I noticed a few Issues regarding flex, But I couldn't really understand what yall's current support for Flex is.

Are you planning on removing it from the entire Library?

If so, What can I do to maintain yalls support?

**Comment by tysongach** [comment]
Are you speaking of CSS flexbox, or Neat’s [flex functions](https://github.com/thoughtbot/neat/blob/master/app/assets/stylesheets/grid/_private.scss)?

**Comment by joelcoxokc** [comment]
Neats Flex functions. 

I would like to Flex-Box  with 
span-columns()

**Comment by wardpenney** [comment]
To be honest, I haven't tried to use Neat for flexbox grid layout yet. I have found that using Flex for layout can be risky and requires fallbacks for older browsers. I typically only use Flex for module or smaller level patterns.

**Comment by wardpenney** [comment]
That said, it becomes more stable every day, so it could be useful for Neat to support if fully. Have you tried yet @joelcoxokc?

**Comment by tysongach** [comment]
Not sure I fully understand the issue or question, but here’s a quick CodePen showing Neat working alongside CSS flexbox: http://codepen.io/tysongach/pen/BNXMOd

Closing for now…let us know if that doesn’t help or there’s a specific issue we could look into.

**Comment by joelcoxokc** [comment]
Hey man this is great! Sorry for the delayed reply! I will send a code pen example soon!
