### ISSUE TITLE
outer-container();

### ISSUE THREAD

**Issue by Gouvi** [thoughtbot/neat#370]
Not sure if it's an issue, could just be me sorry.

I have an empty div (.header-image) with a height of 150px. I then created a div below .wrap.

The issue that I am having is that the .wrap with the outer-container() sits at the top of the initial div. The only way I can get it to sit below the initial div is with float: left which breaks the outer-container(). Does the initial .header-image have to contain any content other than specifying the height?

```sass
.header-image {
    @include span-columns(12);
    position: relative;
    height: 150px;
    .wrap {
        @include outer-container();
        position: relative;
    }
}
```
![screen shot 2015-08-14 at 2 11 24 pm](https://cloud.githubusercontent.com/assets/6964274/9268193/639ecf1c-428e-11e5-950e-30bdd9be027a.png)

**Comment by mehlah** [comment]
Is there any reason to nest `.wrap` in `.header-image`
Looking at the screenshot, those two seems different blocks. What layout do you want to get?

**Comment by Gouvi** [comment]
Whoops I wrote that wrong on here, was meant to be:

```sass
.header-image {
    @include span-columns(12);
    position: relative;
    height: 150px;
}
.wrap {
    @include outer-container();
    position: relative;
}
```

Anyway, I ended up doing the following to fix it:
```sass
.header-image {
    @include span-columns(12);
    @include omega();
    position: relative;
    height: 150px;
}
.wrap {
    @include span-columns(12);
    @include omega();
    position: relative;
    .contain {
        @include outer-container();
        position: relative;
    }
}
```

**Comment by mehlah** [comment]
Having the `outer-container()` in the `.contain` class nested in `.wrap`'s `span-columns(12)` is weird.
In most cases, you should have only 1 grid container `outer-container()`, and you can't nest those. Neat doesn't support grids nesting out of the box
