### ISSUE TITLE
How to use/create a simple block grid

### ISSUE THREAD

**Issue by mmjaeger** [thoughtbot/neat#379]
hello
is there a way using bourbon/neat to create a simple block grid to put a standard Wordpress gallery into e.g. 3 columns - I guess applying some negative margin to the gallery container and floating the gallery-items. whatever I try using span-columns doesn't seem to work and using omega seems to be kind of overkill.

thank you in advance for your input.

**Comment by mmjaeger** [comment]
tried flex-grid as well - cannot get it to work.

somebody please help

**Comment by tysongach** [comment]
@mmjaeger Did you take a look at the [example page](http://neat.bourbon.io/examples/), specifically the “Automatic rows” section? Is that what you’re trying to accomplish?

- What doesn’t work when you use `span-columns`?
- Can you provide a CodePen or link to your code?

**Comment by mmjaeger** [comment]
I'm a little hesitant using omega since it has to be reset when collapsing the grid, but I'm sure that could be solved.

another issue I'm having is creating three columns in a row, each 33.33333% with no margin - assumed 'block-collapse' would do the trick but I'm getting 2 columns that are 34....% and one column that is some 31....% wide - not what I would have expected.

**Comment by mmjaeger** [comment]
bump

**Comment by mehlah** [comment]
> I'm a little hesitant using omega since it has to be reset when collapsing the grid, but I'm sure that could be solved.

What do you mean by "collapsing the grid"?
You want a different block grid for smaller screens?
If you want to avoid resetting the omega with bad CSS, you can use mutually exclusive media queries
```scss
  li {
    @include media($small-screen) {
      @include span-columns(6);
      @include omega(2n);
    }

    @include media($large-screen) {
      @include span-columns(3);
      @include omega(4n);
    }
  }
```

Hope it helps.

**Comment by tysongach** [comment]
Closing for now, since we don’t have responses to @mehlah’s questions above. Please re-open if you’re still having issues.
