### ISSUE TITLE
Mixin @include row(table)

### ISSUE THREAD

**Issue by tomcornall** [thoughtbot/neat#385]
See #338 for similar situation

I'm using Neat 1.7.2

#### Mixin causes global table display property

SCSS placed anywhere...
`@include row(table);`
introduces global display property set to table:
`$container-display-table: true !global;`

This means something like this:

```scss
@include span-columns(6);
```

will output:

```css
display: table-cell;
width: 50%;
```

instead of...

````css
float: left;
display: block;
margin-right: 1.69492%;
width: 49.15254%;
```

I took out the `!global` attribute to fix it in my case.

**Comment by tomcornall** [comment]
@tysongach Am I missing something?

**Comment by LeusMaximus** [comment]
I have similar problem.
For example:
```scss
.another-block {
  @include span-columns(10);
}

.block {
  @include row(table);
}
```
In this situation `.another-block` has right styles
```css
.another-block {
  float: left;
  display: block;
  ........
}
```

But if we positioning `.another-block` after `.block` it has wrong styles
```scss
.block {
  @include row(table);
}

.another-block {
  @include span-columns(10);
}
```

```css
.another-block {
  display: table-cell;
  ........
}

**Comment by tomcornall** [comment]
@leusmaximus
As I mentioned you can take out the !global attribute in the scss row settings if you're looking for a fix for this - worked for me.

**Comment by tysongach** [comment]
Try using `reset-display` to set things back to block after using table on an individual row.

**Comment by tomcornall** [comment]
@tysongach 
So you have to apply `reset-display` to everything after `@include row(table)`? 
See: https://github.com/thoughtbot/neat/pull/402

Does that make sense?
