### ISSUE TITLE
What are best practices for RTL/LTR for the neat framework?

### ISSUE THREAD

**Issue by rogerrogers** [thoughtbot/neat#388]
One of the problems of float based frameworks is that they don't automatically reflow for RTL content.

I'm new to bourbon neat, so not sure if I'm doing this properly. I find I'm having to write any neat layout rules twice. Yuck.

To reduce this, I'm creating mixins on the fly, just to reduce the code somewhat. E.g.

```
	@mixin start_form_layout {

		@include media($laptop) {
			@include span-columns(6);
		}
		@include shift(0);

	}
	.ltr & { @include direction-context($ltr) {
		@include start_form_layout;
	}}
	.rtl & { @include direction-context($rtl) {
		@include start_form_layout;
	}}
```

This at least ensures my rules are the same for both ltr and rtl, which is helpful for coding errors. But this still is pretty nasty.

I wonder if there could be a better way?

**Comment by eerkel** [comment]
Follow-up thought:

In the end, producing a layout that replicates for both RTL and LTR requires duplicate CSS (when using the Neat approach/floats). It would be nice if we could set some basic configuration settings that produce this automatically. E.g.

$parent-rtl-classes: rtl, fa (an array of classes that denote RTL content)
$parent-ltr-classes: ltr, en (ditto)
$generate-both-direction-contexts: true;

If $generate-both-direction-contexts = true, then this would produce css for both contexts, prepending the parent selector for scope.

That way, one could simply do:

```
        @include media($laptop) {
            @include span-columns(6);
        }
        @include shift(0);
```

And Neat would produce css for both contexts.

Or, maybe I'm just not groking the Neat approach to creating a layout for content that will be presented in both RTL and LTR.

Cheers!

**Comment by whmii** [comment]
@rogerrogers I feel your pain. Currently, what you have above is "as good as it gets". We are going to develop some improvements to multi grid layouts in 2.0 which in tern should make contexts/ltr+rtl projects easier to handle.
