### ISSUE TITLE
calculation of Column width and other problems

### ISSUE THREAD

**Issue by bunower** [thoughtbot/neat#389]
Hello,
i am really new to Neat, so i am trying to use it for my upcoming projects.
But there are some problems.
![neat_problems](https://cloud.githubusercontent.com/assets/7440674/11092529/7112b12c-8884-11e5-9980-a7208d65a04d.jpg)

1.The gutter between the yellow blocks need to be the same as main gutter.
How can i realize this.

2.And if i add to the yellow blocks  span-columns(6,block-collapse) they have to bet exact 50%,
but now they are 51.1788%;

**Comment by mehlah** [comment]
With Neat you can't nest grids and use a `span-columns(6)` for your yellow blocks, considering their parent (the green box) is a 12-columns grid nested in your main grid (red one).
I guess it's what you do.

I suggest using a simple margin or padding for your yellow boxes equal to the Sass variable `$gutter` which contains the exact width of the gutter used by the grid.

Hope it helps

**Comment by bunower** [comment]
I did not understand it very well.
Can you give me an example.
Neat works at top level for grids?
So if i nest Grids it not really works fine.
But if i cant use span-columns for the yellow block, so how i can calculate the width?
width = (100% - maingutter) / 2 ?

**Comment by mehlah** [comment]
Yes!
Here is a Pen http://codepen.io/mehlah/pen/rOoLGx?editors=110

**Comment by tysongach** [comment]
Closing due to lack of response; @bunower feel free to let us know if you still are having issues.
