### ISSUE TITLE
@media for retina detection

### ISSUE THREAD

**Issue by marchdoe** [thoughtbot/neat#39]
Curious if neat supports something like this

``` CSS
@media only screen and (min--moz-device-pixel-ratio: 2), 
only screen and (-o-min-device-pixel-ratio: 2/1), 
only screen and (-webkit-min-device-pixel-ratio: 2), 
only screen and (min-device-pixel-ratio: 2) { 

}
```

I looked at the documentation but nothing stood out as the answer.

**Comment by designbyadrian** [comment]
I'd like to add that this feature has been moved in Bourbon 5. I don't know where yet, but using v4, so here's the link:

https://github.com/thoughtbot/bourbon/blob/v4-stable/app/assets/stylesheets/css3/_hidpi-media-query.scss
