### ISSUE TITLE
Add contrib site to make future updates easier

### ISSUE THREAD

**Issue by whmii** [thoughtbot/neat#390]
Came  across a similar issue with bitters but contributing to neat is difficult when there is no simple way to spin up a site and make edits to neat. I think we should consider adding a simple Neat example site to make contributing easy and fun! :heart: :heart: :heart: :heart: :heart: 
https://github.com/thoughtbot/bitters/pull/185

@wardpenney @tysongach

**Comment by tysongach** [comment]
:+1: I think that would be great!

**Comment by tysongach** [comment]
This has been done: https://github.com/thoughtbot/neat/tree/master/contrib
