### ISSUE TITLE
Media query problem using ems

### ISSUE THREAD

**Issue by rsdrsd** [thoughtbot/neat#398]
I have some media queries in neat using ems. When using pixels you can do something like:

    @media  (max-width: 640px) { ... }
    @media (min-width: 641px) and (max-width: 768px) { ... }

When using ems these kind of queries would look like:

    @media  (max-width: 40em) { ... }
    @media (min-width: 41em) and (max-width: 48em) { ... }

As you can see in the first em media query there is 40 em and in the second media query there is 41 em. If we consider 1em is 16px, there is a gap of 16px. How can I handle this? 

I could change the 41 em to 40 em, but then I have two media queries for 40em. This is especially annoying when using neat in combination with the outer-container and omega mixin in both media queries with different parameters for the omega mixin, for example 2n and 3n.

The problem is, is that the media query will satisfy for 40em both the 2n and 3n css rules, which gives some strange layouts. Now I can use the omega reset mixin. But I have read that this isn't good practice.

Am I missing something? Anyone has some good ideas to handle breakpoints using ems. I also could use only min-with in the media query, but then I still need the omega reset mixin.

**Comment by sadiqevani** [comment]
@rsdrsd use em() from bourbon, em() takes pixels and convert them to ems.

Example:

@media  (max-width: em(640)) { ... }
@media (min-width: em(641) and (max-width: em(768)) { ... }

**Comment by whmii** [comment]
@rsdrsd in this sort of situation, I would recommend simply sticking with pixels in your media queries. There is nothing objectively "better" about using ems.

Closing for now but feel free to reopen if you encounter any issues.
