### ISSUE TITLE
Issue with Bourbon / Neat Grid - grids dont align correctly

### ISSUE THREAD

**Issue by sadiqevani** [thoughtbot/neat#410]
am new to Bourbon / Neat framework, and the past 2 days i've been setting my environment up, but i am having issues configuring the Grid.

The issue is that no matter how much i try, there are some spacing issue when it comes to the grid, there is a small space in between columns in the grid, which is giving me a headache, and i have no idea what is causing it.

<img width="862" alt="screenshot 2016-02-09 13 11 43" src="https://cloud.githubusercontent.com/assets/2134415/12907728/e4d5cf06-cf31-11e5-89c8-1548b1c0a391.png">

As you can see from the image, the right column, is slightly on the left, is this a common occurrence in neat?

Thank you in advance.

**Comment by tysongach** [comment]
Hi @sadiqevani! Please see: https://github.com/thoughtbot/neat#why-are-the-elements-not-properly-aligned-with-the-visual-grid
