### ISSUE TITLE
Neat Changing Display Context - Warnings

### ISSUE THREAD

**Issue by sadiqevani** [thoughtbot/neat#411]
Hello,

So, i am starting to get used to Neat, and i think its a pretty cool tool compared to other options outside, but there are some concepts which are still pretty new to me.

Now, Neat provides two type of displays, block and table, and both of them can be changed using the mixins row(), display-context(), and some other mixins, but generally these mixins only change/assign a variable that changes the coming columns/rows to the appropriate display value. 

Since this variable gets inherited from mixins after declaring, i need to force reset it to the default one (block).

But now i get the following warnings from SASS:

```
 WARNING: The $display argument will be deprecated in future versions in favor of the display(){...} mixin.
        on line 11 of node_modules/bourbon-neat/app/assets/stylesheets/settings/_disable-warnings.scss
        from line 39 of node_modules/bourbon-neat/app/assets/stylesheets/grid/_row.scss
        from line 28 of app/css/core/_heroes.scss
    
    WARNING: The $display argument will be deprecated in future versions in favor of the display(){...} mixin.
        on line 11 of node_modules/bourbon-neat/app/assets/stylesheets/settings/_disable-warnings.scss
        from line 39 of node_modules/bourbon-neat/app/assets/stylesheets/grid/_row.scss
        from line 80 of app/css/core/_heroes.scss
    
    WARNING: Resetting $display will be deprecated in future versions in favor of the display(){...} mixin.
        on line 11 of node_modules/bourbon-neat/app/assets/stylesheets/settings/_disable-warnings.scss
        from line 64 of node_modules/bourbon-neat/app/assets/stylesheets/grid/_to-deprecate.scss
        from line 106 of app/css/core/_heroes.scss
```

So, i tried to look up the display() mixin, but the mixin had only flexbox properties, does this mean that when neat hits a major version it will stop supporting block and table displays ?

And should i ignore these warnings? Or am i doing something wrong?

Regards
Sadi

**Comment by sadiqevani** [comment]
```
WARNING: The $display argument will be deprecated in future versions in favor of the display(){...} mixin.
    	on line 11 of node_modules/bourbon-neat/app/assets/stylesheets/settings/_disable-warnings.scss
    	from line 39 of node_modules/bourbon-neat/app/assets/stylesheets/grid/_row.scss
    	from line 28 of app/css/core/_heroes.scss

    WARNING: The $display argument will be deprecated in future versions in favor of the display(){...} mixin.
    	on line 11 of node_modules/bourbon-neat/app/assets/stylesheets/settings/_disable-warnings.scss
    	from line 39 of node_modules/bourbon-neat/app/assets/stylesheets/grid/_row.scss
    	from line 80 of app/css/core/_heroes.scss

    WARNING: Resetting $display will be deprecated in future versions in favor of the display(){...} mixin.
    	on line 11 of node_modules/bourbon-neat/app/assets/stylesheets/settings/_disable-warnings.scss
    	from line 64 of node_modules/bourbon-neat/app/assets/stylesheets/grid/_to-deprecate.scss
    	from line 106 of app/css/core/_heroes.scss

    WARNING: The $display argument will be deprecated in future versions in favor of the display(){...} mixin.
    	on line 11 of node_modules/bourbon-neat/app/assets/stylesheets/settings/_disable-warnings.scss
    	from line 39 of node_modules/bourbon-neat/app/assets/stylesheets/grid/_row.scss
    	from line 58 of app/css/core/_tables.scss

    WARNING: The $display argument will be deprecated in future versions in favor of the display(){...} mixin.
    	on line 11 of node_modules/bourbon-neat/app/assets/stylesheets/settings/_disable-warnings.scss
    	from line 39 of node_modules/bourbon-neat/app/assets/stylesheets/grid/_row.scss
    	from line 87 of app/css/core/_tables.scss

    WARNING: Resetting $display will be deprecated in future versions in favor of the display(){...} mixin.
    	on line 11 of node_modules/bourbon-neat/app/assets/stylesheets/settings/_disable-warnings.scss
    	from line 64 of node_modules/bourbon-neat/app/assets/stylesheets/grid/_to-deprecate.scss
    	from line 125 of app/css/core/_tables.scss

    WARNING: The $display argument will be deprecated in future versions in favor of the display(){...} mixin.
    	on line 11 of node_modules/bourbon-neat/app/assets/stylesheets/settings/_disable-warnings.scss
    	from line 39 of node_modules/bourbon-neat/app/assets/stylesheets/grid/_row.scss
    	from line 127 of app/css/core/_wizard.scss

    WARNING: The $display argument will be deprecated in future versions in favor of the display(){...} mixin.
    	on line 11 of node_modules/bourbon-neat/app/assets/stylesheets/settings/_disable-warnings.scss
    	from line 39 of node_modules/bourbon-neat/app/assets/stylesheets/grid/_row.scss
    	from line 153 of app/css/core/_wizard.scss

    WARNING: Resetting $display will be deprecated in future versions in favor of the display(){...} mixin.
    	on line 11 of node_modules/bourbon-neat/app/assets/stylesheets/settings/_disable-warnings.scss
    	from line 64 of node_modules/bourbon-neat/app/assets/stylesheets/grid/_to-deprecate.scss
    	from line 170 of app/css/core/_wizard.scss
```

**Comment by wardpenney** [comment]
Hi @sadiqevani, it looks like you are wanting to do one grid as `block` and then another grid later as `table`? The forced reset you are doing should work fine, although you are getting the annoying deprecation warnings. You could try using the `display-context()` for your table case, and then just letting it remain in that local variable scope, thereby defaulting back to `default` which will be treated as block.

And as for future deprecations, this still looks like it remains true. Would you mind posting your source for the grids you are making, then I can see a little bit better the goal you're looking to achieve?

**Comment by sadiqevani** [comment]
Hey @wardpenney ,

So, the idea is that generally i would like to use the block/float system for the grid, since i am not sure what implications will be if i converted the grid into table layout.

I am using tables, to generate some specific components, which need to be centered vertically, but at the same time have a grid system.

So, i guess the way i am going it right now seems fine, but probably its not future proof, in case i want to upgrade to a new Neat version?

**Comment by wardpenney** [comment]
@sadiqevani in your situation, I would use the `outer-container` and `span-columns` mixins to work with a floated grid. Then for the parts you need vertical centering, maybe construct something for just that pattern with flexbox, table or other vertical centering tricks. I personally don't use table layout for the whole page.

**Comment by sadiqevani** [comment]
@wardpenney i am going to try to keep like this initially, if i have problems, i am going to change it, most of the CSS is pretty modular, so i can change things without sending everything to hell :smile:

**Comment by wardpenney** [comment]
@sadiqevani nice, modular is the way to go!!
