### ISSUE TITLE
Span-columns with table context not filling the space!

### ISSUE THREAD

**Issue by sadiqevani** [thoughtbot/neat#412]
Hello,

Working with Neat, i am trying to make a grid that helps me center items vertically, and to achieve this i am using the table layout context.

But when i need to make a nested columns, with table context, the nested columns dont fully expand, they are wrapping around the element width.

To solve this i need to create a container, that sets its display again to table, so i can use "nested" items.

My question is: Is there a better way to achieve this?

Regards
Sadi

**Comment by whmii** [comment]
@sadiqevani I think flexbox may be a better option for what you are trying to achieve. Nested table contexts are pretty unreliable unfortunately.

Alternatively (if flexbox is an option) it may be preferable to write some custom stylesheets for this section that are outside the grid system.

**Comment by sadiqevani** [comment]
@whmii understood, though this is a bit outdated since i already figured a way out :D.
