### ISSUE TITLE
Visual grid doesn`t match with real grid.

### ISSUE THREAD

**Issue by heyas** [thoughtbot/neat#414]
Image: [http://joxi.ru/eAOL7oyI4Dlebr](url)
What i'm doing wrong?

**Comment by tysongach** [comment]
Hi @heyas! The link you provided appears to be broken, so I’m unable to gain some context. But this FAQ in the readme explains why the visual grid does not always match up: https://github.com/thoughtbot/neat#why-are-the-elements-not-properly-aligned-with-the-visual-grid

**Comment by heyas** [comment]
@tysongach Sorry, I had first read the FAQ before asking questions. My fault.

**Comment by tysongach** [comment]
@heyas No worries!
