### ISSUE TITLE
index.js not in v1.7.2 NPM package?

### ISSUE THREAD

**Issue by deakster** [thoughtbot/neat#416]
After doing an `npm install bourbon-neat` and then trying to `require("bourbon-neat")` in node, I get the error:

`SyntaxError: /app/available_modules/1456578798000/bourbon-neat/app/assets/stylesheets/_neat.scss:7 @import "neat-helpers"; ^ Unexpected token ILLEGAL`

The reason appears to be that the [index.js](https://github.com/thoughtbot/neat/blob/master/index.js) file that is in the github repo isn't in the bourbon-neat folder that's installed via NPM, so we don't get back the object with an `includePaths` field. Instead, the require() call seems to pick the _neat.scss file, which it tries to load as a javascript file.

You can re-create the issue here:
https://tonicdev.com/npm/bourbon-neat

**Comment by tysongach** [comment]
We haven’t had a chance to cut the release yet.

**Comment by tysongach** [comment]
@deakster We just released `1.7.3`, which includes `index.js`: https://github.com/thoughtbot/neat/releases/tag/v1.7.3
