### ISSUE TITLE
request for documentation on installation without Ruby or NPM

### ISSUE THREAD

**Issue by tvmaly** [thoughtbot/neat#431]
I would like to use the whole suite of Bourbon and Neat etc, but I work with a Makefile for my Go projects.  Could you add some instructions on how to install the libraries without using Ruby or Node ?

**Comment by sopvop** [comment]
As I understand it, you just need `app/assets/stylesheets` folder. I have no idea why webdevs like to complicate things so much.

**Comment by tvmaly** [comment]
I figured it out.  I ended up using Ruby to do the install of the stable versions.  Then I just installed the files in a directory and hooked it up to Makefile that calls out to libsass

**Comment by bowlingforsoap** [comment]
With Bourbon 5 this doesn't seem an option anymore. The stable v4 is available on GitHub, though.

PS. If you are using Dreamweaver, it can install Bourbon for you: https://helpx.adobe.com/dreamweaver/using/css-preprocessors.html
