### ISSUE TITLE
Two columns split 50/50

### ISSUE THREAD

**Issue by bjorn2404** [thoughtbot/neat#433]
I'm probably missing something but when trying to set up two columns side by side with no space between with @include span-columns(6) I can't seem to make both widths the same. I've tried block-collapse and the omega mixin but one column always seems to be off by what I think is the gutter width.

**Comment by ayalan** [comment]
If you want two columns side-by-side without the gutter between, you probably want to use a table grid using
`@include fill-parent();`
`@include row(table);`

(See table grid in the [examples page](http://neat.bourbon.io/examples/))

**Comment by bjorn2404** [comment]
Ok, thanks.
