### ISSUE TITLE
Is it necessary to include clear:both to an outer-container?

### ISSUE THREAD

**Issue by christiantype** [thoughtbot/neat#434]
I have a section underneath my header and I am noticing that when viewing the section in Chrome's inspector, touches the top of the viewport. 

When I add `clear:both;` to the section, the section goes properly underneath the header.

**Comment by wardpenney** [comment]
Inside your `outer-container` you should also have en element with `span-columns`, even if it's `span-columns(12 of 12)` or another full-width grid column. The `outer-container` already contains a clearfix, and that will give height to the container equal to the size of the floated columns within. 

@christiantype does that help?

**Comment by whmii** [comment]
Closing issue, reopen if you still need help.
