### ISSUE TITLE
Breakpoint SASS compiling issue (incorrect CSS output)

### ISSUE THREAD

**Issue by simonlayfield** [thoughtbot/neat#437]
Hey there,

A slight issue I found when modifying the grid settings.

**style.scss**

    @import 'grid-settings';
    @import '../node_modules/bourbon-neat/app/assets/stylesheets/neat';

**_grid-settings.scss**

    @import "../node_modules/bourbon/app/assets/stylesheets/bourbon";
    @import "../node_modules/bourbon-neat/app/assets/stylesheets/neat-helpers";

    $column: 90px;
    $gutter: 1px;
    $grid-columns: 12;
    $max-width: 100%;

    $small: new-breakpoint(max-width 480px 4);
    $medium: new-breakpoint(min-width 481px max-width 768px);
    $large: new-breakpoint(min-width 769px);

In **style.scss**, the following:

    @media($small) {
                background: #00aeff;
           }

renders in the browser as

    @media (max-width 480px 4) {
    }

Is there a reason why these wouldn't be compiling?

Using **Sass 3.4.16 (Selective Steve)**.

Thanks in advance for any help.

**Comment by tysongach** [comment]
@simonlayfield It looks like you might have a syntax issue. Neat’s `media` mixin can be used with Sass’s `@include`, but you have `@media` (`@media` is the CSS _output_). Here’s what it should look like:

```scss
@include media($small) {
  …
}
```

Reference: http://thoughtbot.github.io/neat-docs/latest/#media

**Comment by tysongach** [comment]
Closing due to lack of response.

**Comment by simonlayfield** [comment]
Apologies! Yeah this is right, thanks for your help!
