### ISSUE TITLE
neat 2.0 grid

### ISSUE THREAD

**Issue by mmjaeger** [thoughtbot/neat#439]
Hello
had a look at the column mixins - you're applying the gutter as margin-left - I was surprised to see however, that you're not compensating for the left margin by applying a negative gutter to the parent container?

**Comment by tysongach** [comment]
@mmjaeger Are you speaking about https://github.com/thoughtbot/neat/pull/427? If so, can you put this comment in that PR, so to keep everything contextual? Also, keep in mind that the work on 2.0 is still very rough and not fully fleshed out.
