### ISSUE TITLE
Respect ratio when using span-columns

### ISSUE THREAD

**Issue by Sathors** [thoughtbot/neat#441]
Hi,

I was wondering if there was any way to respect an element ratio when using span-columns.

My use case is using background images in the grid. When I resize the window horizontally, the width gets modified, but the height stays the same, which results in my image distorted.

Is there a conventional way to reach that using neat?

Thanks for your help

**Comment by joshuaogle** [comment]
Hi @Sathors. You could give [this trick a try](https://css-tricks.com/snippets/sass/maintain-aspect-ratio-mixin), but there isn't really a way to do this using CSS. Normally this would be done using Javascript.

**Comment by joshuaogle** [comment]
Closing this issue since it turns out it isn't specific to Neat, it's just a limitation of CSS. Feel free to ask more questions though if you need any help finding a solution.

**Comment by Sathors** [comment]
Hi @joshuaogle.

Thanks for your help. Actually I already saw this trick, and tried to implement it without success.
My skills in CSS are not the best, so I thought somebody already had a solution.
I will try to tinker with it a bit.

Using this trick as-is works, but then I don't enjoy neat horizontal resizing.

Do you think it would be a good candidate for inclusion in thoughbot/refills? A full component maybe with JS, integrating with the framework?
Because I would think it to be quite a common requirement (for background images mainly).

**Comment by joshuaogle** [comment]
That trick relies on some pretty specific circumstances, so it doesn't work in a lot of cases. Yeah, that might be a good Refills component, good idea. I'm not sure it's one that comes up often enough to warrant maintenance, but it's also pretty simple JS.

For background images I've started using [object-fit](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) with a polyfill for IE and it makes some of those much much simpler.
