### ISSUE TITLE
Design Question/Suggestions

### ISSUE THREAD

**Issue by rwboyer** [thoughtbot/neat#443]
Not an "issue" with neat more of a question.

Have a typical main content area/aside area made up of 8 and 4 columns via neat for a total of 12. All is well and good until someone wants the aside area to have a different colored background than the content columns. NBD right? Except they want it to extend all the way past the outer row container to the edge of the browser.

Any suggestions?

the typical kludge of massive negative margin and positive padding does not work at all for the aside container with @include columns(4). 

Thanks

RB

**Comment by whmii** [comment]
@rwboyer the classic solution for this is to have a wrapping `div` that goes around the container/row

**Comment by whmii** [comment]
however, if you have 1 big row for all your content, you may have to break it up into multiple ones. A screenshot for these things is always helpful.

**Comment by whmii** [comment]
Hope this helps! Closing for now.

Feel free to reopen if you are still encountering issues. 👍

**Comment by rwboyer** [comment]
Thanks... don't need the color to extend across whole page. Just the 4 columns say on the left side and bleed to the left no mater what the browser width.

IE

    <outer row of max width------------------------------------------------->
<-------Yellow------><---------------------Normal background------------------>
    <---4 cols-------><-------------------------8 cols-------------------------->


typically you can push that background on left with massive negative margin then equal padding to back on but this doesn't work on a neat div span columns....

Just wondered if anyone had a quick easy solution they've used?

RB

**Comment by whmii** [comment]
@rwboyer If i'm not mistaken, I think you may be able to do something like the following (hold on to your hats because things are about to get weird)

```scss

$grid-columns: 12;

.container {
  @include outer-container(900px);
}

.inner {
  @include span-columns(20);
  @include shift(-4);
}

```

Hope this helps 😄

**Comment by whmii** [comment]
@rwboyer You inspired another issue and I went ahead and tried it out! see the screenshot below:

![screen shot 2016-07-07 at 11 09 02 am](https://cloud.githubusercontent.com/assets/2489247/16658224/890af184-4433-11e6-922f-8527d02266f0.png)

**Comment by whmii** [comment]
tagging @tysongach for the lols
