### ISSUE TITLE
Browser not Recognizing a Breakpoint set in Neat

### ISSUE THREAD

**Issue by loganegbert** [thoughtbot/neat#444]
Hi All,

I'm having some trouble with getting browsers to recognize my $tablet breakpoint and load the number of columns i've set for that in grid_settings. Here's what I have for that file:

```scss
@import "bourbon/bourbon";
@import "neat/neat-helpers";

//Change to Grid 
$max-width: em(1280);

// Define your breakpoints
$desktop: new-breakpoint(min-width 1024px 12);
$tablet: new-breakpoint(max-width 768px 8);
$mobile: new-breakpoint(max-width 480px 6);
```

However, here's what the site looks like in developer tools when set to iPad, which should trigger that breakpoint. It still has 12 columns and none of my styling displays:
![screen shot 2016-06-05 at 8 23 34 pm](https://cloud.githubusercontent.com/assets/13635079/15811231/727fd68c-2b5b-11e6-90fe-5acf6cb71561.png)

I'm using:

```scss
@include media($tablet) {
}
```
to call up that styling. But it's almost as if the breakpoint is being completely ignored. 

Any ideas what might be going on here?

**Comment by designbyadrian** [comment]
What's the CSS output?

**Comment by whmii** [comment]
Yea, it would be great to see what is being output. Honestly my first guess is that 768 may just be to close to the exact # of how pixels on your screen. try making it `800px` for the lolz. I bet it would fix the issue. 

Closing for now, feel free to reopen if the issue continues.
