### ISSUE TITLE
Breakpoints problem

### ISSUE THREAD

**Issue by madsciencepro** [thoughtbot/neat#445]
My code sample is below. The mobile and tablet breakpoints work fine. The Desktop level doesn't line up correctly as 2 cols and 10 cols. What am I missing? 

https://codepen.io/madsciencepro/pen/VjaXRO

**Comment by whmii** [comment]
Because you are using a mobile first ( using `min-width`) approach (which is a good thing), you need to order your media queries from smallest → largest. I have created a fork of your pen that shows how this would work.

https://codepen.io/whmii/pen/aZNXxJ

**Comment by madsciencepro** [comment]
Aha! I figured it was something simple I was missing because I'd been staring at it way too long. Thanks!
