### ISSUE TITLE
Neat 1.7.4 and bourbon 5.0.0.beta.6

### ISSUE THREAD

**Issue by yndrelbosch** [thoughtbot/neat#446]
I'm using the beta gem for bourbon, but for some reason the neat gem won't install sure to being unable to locate a valid gem bourbon >=4.0

Is that not meaning equal to or greater than? If so, then 5.0 should logically work xd

**Comment by whmii** [comment]
Hi, At this time `neat 1.7.4` does have a `bourbon 4.0` dependancy. Since there is not a strong case for why this is the case, we are going to update Neat to remove this dependency on Bourbon in https://github.com/thoughtbot/neat/pull/440

**Comment by tysongach** [comment]
@yndrelbosch You can now use Neat `1.8`, which no longer requires Bourbon.
