### ISSUE TITLE
Remove mentions of Bourbon from the website

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/neat#449]
Now that Neat [no longer has a Bourbon dependency](https://github.com/thoughtbot/neat/commit/441549048f59b2cc8264e4a5a4496f9e934d69ef), we need to update the website.

For example, “A lightweight semantic grid framework for Sass and Bourbon.” could/should read “A lightweight, semantic grid framework.” (like our readme here on GitHub).

We should probably update the tagline for the website _and_ the readme, and include “Sass”: “A lightweight semantic grid framework for Sass.”

**Comment by whmii** [comment]
Fixed in https://github.com/thoughtbot/neat/pull/454
