### ISSUE TITLE
Golden ratio columns

### ISSUE THREAD

**Issue by anartfulscience** [thoughtbot/neat#453]
Hello,

I'd like to use golden ratio column widths in neat.
Is this possible?

Thanks, Stephen

**Comment by whmii** [comment]
@anartfulscience I'm assuming that you mean something like this → http://www.goldennumber.net/wp-content/uploads/golden-ruler-card.gif

At this time, true support for this feature is not available. If you are really looking for something like this (what I am about to propose is super crazy but hear me out) would be to have a 100 column grid and then round your golden ratio values to their nearest approximate. But you would have to keep track of the page position manually.

Hope this helps

**Comment by anartfulscience** [comment]
Kinda, 3-5 columns would do for most applications really. It's usually to divide the main content areas using 1.618.

I've tried to integrate a golden ratio sass mixin modified from a 3rd party and tried to line it up using a 24 column neat grid with 1em column and gutter but it's just out.

You can find the mixin here if it helps;
https://engineering.fundingcircle.com/blog/2015/06/08/golden-ratio-grid-system-in-sass/

Cheers, Stephen

**Comment by whmii** [comment]
Yea, unfortunately the behavior like you described above is a bit outside the scope of Neat. It is also possible to have libraries for 2 grid systems running concurrently so you could import and use Neat as well as adding a custom system to do the behavior described in the article you linked.
