### ISSUE TITLE
Add Neat 2.0 ltr/rtl support

### ISSUE THREAD

**Issue by whmii** [thoughtbot/neat#469]
International projects have unique needs, one of which is support for ltr/rtl support. Ideally a user would be able to switch directions with use of a single setting. I have not seen this done successfully in other frameworks but I believe it to be successful.

I would love to hear from those who work in multiple languages and text directions and their successes and failures in doing so. This will likely have a significant impact on how this feature manifests.

**Comment by whmii** [comment]
@jensimmons recommended reaching out to the Drupal community.

Will invesigate

**Comment by whmii** [comment]
This will likely not make 2.0 but is a great candidate for a 2.X

**Comment by whmii** [comment]
Requires user data to resolve.
@whmii to make a survey about some of these features and reach out to the community.

**Comment by whmii** [comment]
> Oh I misread your first post..so to answer your question:
> 
> Yes RTL float system is more intuitive since everything in terms of usability and ux in general is mirrored..so you'll find main" content blocks on the right and the sidebar on the left..etc
> 
> I usually work on either only Arabic(rtl) websites or multilingual websites that include at least Arabic and English(French comes next).
> The first case would not differ much in terms of the grid..I know lots of developers in the region here who use Bootstrap; they use grid classes + push/pull helper classes to switch their divs' position..
> But when it comes to bidirectional websites..it'll get ugly with Bootstrap, unless you separate your markup too(which is even uglier).
And I'm only here talking about grids; using frameworks' other ui components is a different story.
> 
> Foundation on the other hand, their rtl support makes everything easier..my sass is unified..and my output is two mirrored .css files.
> 
> Before CSS preprocessors, I would start with LTR version and then work on the RTL one. Because Drupal(and WordPress too) loads both(styles.css and styles-rtl.css), I would override only the horizontal positioning attributes in the -rtl.css file. It was a very time consuming and boring process.
> 
> All of the multilingual/bidirectional websites I've worked on share the exact layout but mirrored...what's left becomes on the right and vice versa.
> Another non-layout difference is the font-size..Arabic fonts are usually smaller for some reason. A base font of 12px in English becomes 14px in Arabic(Tahoma for example). Sometimes this requires some layout alters(but this is very rare).
> 
> By the way, I really like your framework's logic..I personally use other frameworks' grid mixins heavily for the same reasons.
> 
> I hope my answers help you with your framework.
> 
> Layal

— crosspost from https://groups.drupal.org/node/513253#comment-1150039

**Comment by catherine-jones** [comment]
@whmii I work for the DTO in Australia we are similar to 18F in the US. We will eventually need to translate a lot of our digital products into other languages so I would be keen to help out with this feature.

**Comment by whmii** [comment]
@catherine-jones I will work out a basic prototype that will flip the float and push/pull behavior and we'll see how it goes from there. 👍 👍 👍

**Comment by whmii** [comment]
I have created a PR for this feature. Once merged, I will close this issue

**Comment by whmii** [comment]
done :P
