### ISSUE TITLE
Update change log

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/neat#471]
- The [change log](https://github.com/thoughtbot/neat/blob/neat-2.0.0/NEWS.md) needs some updating, particularly for Neat 2.0, with so many breaking changes
- I think we should also rename it from `NEWS.md` to `CHANGELOG.md`, as it is more clear to what it is, and also matches Bourbon’s nomenclature: https://github.com/thoughtbot/bourbon/blob/master/CHANGELOG.md

**Comment by whmii** [comment]
@tysongach I also noticed it's wildly out of date. Think we should burn it down and start anew?

**Comment by whmii** [comment]
Oh, we can just pull the info from https://github.com/thoughtbot/neat/releases

**Comment by tysongach** [comment]
> Think we should burn it down and start anew?

Nooooo…the opposite. The change log needs to tell a clear story of what has changed to our users so that they can keep their code in-shape and working.

It’d be great to backfill, but just getting the latest stuff in would be helpful.

**Comment by whmii** [comment]
https://github.com/thoughtbot/neat/pull/474
