### ISSUE TITLE
dynamic gutter

### ISSUE THREAD

**Issue by rostixman** [thoughtbot/neat#476]
I'm trying to find how to set different gutter values depending on media query. Is it possible?

**Comment by whmii** [comment]
Hi @rostixman, Which version of neat are you using?

**Comment by rostixman** [comment]
Hi @whmii, I use neat 1.7.4

**Comment by whmii** [comment]
Unfortunately not. While I have not tried it, I beleve you can place a `$gutter: XXX;` in the media query at the top and that new gutter value will stay scoped to the objects within the MQ.

I'll put together a codepen in a bit and take a look.

**Comment by whmii** [comment]
Darn, unfortunately you can not reset the gutter width w/in the scope of a mediaquery. see https://codepen.io/whmii/pen/aZNXxJ

This is not currently supported. Functionality for this will exist in 2.0, however that is not recommended for public use quite yet.

**Comment by whmii** [comment]
You can check out the upcoming work on custom gutters & grids w/in media queries at https://github.com/thoughtbot/neat/pull/478
