### ISSUE TITLE
Add custom grid documentation

### ISSUE THREAD

**Issue by whmii** [thoughtbot/neat#479]
Currently, you can create a custom grid like:

```
$my-super-cool-grid: (
  columns: 120000,
  gutter: 2px,
);
```

and then pass it directly in to one of the mixins such as `@include grid-column(6, $my-super-cool-grid);` but this is basically undocumented. Since it is a general property, not sure where to put this except maybe somewhere in the _settings.scss

**Comment by tysongach** [comment]
@whmii Have you thought about encapsulating all grids into one, nested map? Something like:

```scss
$neat: (
  "small": (
    "min-width": 0,
    "columns": 6,
    "gutter": 1rem,
  ),
  "medium": (
    "min-width": 40rem,
    "columns": 12,
    "gutter": 2rem,
  ),
);
```

**Comment by whmii** [comment]
@tysongach I have but that seems like such a difficult thing to handle, both from a user side of understanding what's going on, but also from a code perspective. I believe it would add a lot of complexity to the code base. 

As a basic example, neat would need to understand that small has a min-width of zero which then means it should be the default grid, unless there are multiple grids with min-width: 0 and then do something else.

I would be interested in getting some initial traction with maps as settings, since this doesn't feel like a clean win to me.

However I do feel like this would be a great addition in a future version.

**Comment by whmii** [comment]
I will add the core documentation for this after launch. right now I want to focus on documentation of the core feature set and then expand on more "advanced functionality" later.
