### ISSUE TITLE
`grid-media()` mixin is currently untested

### ISSUE THREAD

**Issue by whmii** [thoughtbot/neat#494]
use https://github.com/thoughtbot/neat/blob/master/spec/neat/media_spec.rb for refference

**Comment by whmii** [comment]
https://github.com/thoughtbot/neat/pull/495 added basic coverage for `grid-media` in that it it makes sure that the classes appear within a media query of a given type. It does not yet check and make sure that the the local `$neat-grid` has ben replaced. this may be fine but we'll see.

**Comment by whmii** [comment]
Consider this half done for now.

**Comment by kgcreative** [comment]
In practical usage, i'm finding that grid-media() is less practical than wrapping @include grid-column(n of n) in a media query. The (n of n) convention maxes complex layouts with multiple nesting really easy to understand and parse.

**Comment by whmii** [comment]
I agree within the context of custom grid column count. The real power of the `grid-media` mixin is to have different gutters across multiple screen sizes, aka skinny gutters on mobile and big gutters that take advantage of the space on desktop.

**Comment by kgcreative** [comment]
oh snap! I hadn't even considered varying gutters. Yes, I can see where this would be an extremely useful use-case.
