### ISSUE TITLE
Adding a max-width for $custom-grid

### ISSUE THREAD

**Issue by nickngqs** [thoughtbot/neat#499]
I'm just wondering is it better to allow an additional input for max-width for the custom grid media. Since it will be useful in some cases where you need to target a specific breakpoint (min-width to max-width)? A good example would be problems during overriding when using nth-child (think omega (omega reset) problem in Neat 1.0).

But of coz, I can just use a simple bp mixin, but just wondering if it's good for Neat to have. Since, if i were to use my own own bp mixin, then technically the media in the custom grid is abit redundant.

What do you guys think?

**Comment by kgcreative** [comment]
You would use `$grid-media` with `$custom-grid` for that. See http://thoughtbot.github.io/neat-docs/2-0-0-beta-1/#Grid media

I believe grid media accepts either a single number (which assumes min-width) or a string, which gets passed through to the breakpoint.

**Comment by whmii** [comment]
Yep, @kgcreative is correct. I'm going to pull a bit from the docs here:

> [Grid media] …Creates a media query in which custom grid properties can be defined. Add the media property to your custom grid settings map and add the media you would like to scope to. If only a number is defined, it is assumed this is a min-with value. Your custom grid can then be passed to the mixin.

Basically in this context, if you wanted to use a custom grid in conjunction with max width properties, You might be something like the following:

```
$my-cool-container-max-width: 1200px;

$my-cool-custom-grid: (
  columns: 12,
  gutter: 20px,
  media: $my-cool-container-max-width,
);

.my-cool-container {
    @include grid-container;
    max-width: $my-cool-container-max-width;
}

```

**Comment by junkin77** [comment]
In neat 2 how would one apply a style just to a particular size range e.g.tablet-only? In neat v1 I did this like this: $tablet-only: new-breakpoint(min-width 48em max-width  63.95em 24);

**Comment by whmii** [comment]
@junkin77 you would use the `grid-media()` mixin for that. http://neat.bourbon.io/docs/latest/#grid-media

As in the example it would look something like

```
$tablet-only-grid: (
  columns: 12,
  gutter: 50px,
  media: "min-width 48em max-width 63.95em",
);

.element {
  @include grid-column(3);

  @include grid-media($custom-neat-grid){
    @include grid-column(6);
    background: blue;
  }
}
```

**Comment by tysongach** [comment]
@whmii In your example above, wouldn’t `@include grid-media($custom-neat-grid)` be `@include grid-media($tablet-only-grid)`?

**Comment by junkin77** [comment]
Ah, so I enter a string. "min-width 48em max-width 63.95em" didn't do it but if I enter "(min-width: 48em) and (max-width: 63.95em)" it works, so example would look something like:
$tablet-only: (
     columns:$columns, 
     gutter:$gutter, 
     media: "(min-width: 48em) and (max-width: 63.95em)",
);

**Comment by whmii** [comment]
@tysongach Good catch, I forgot to update that.

@junkin77 Nice! I always end up needing to do some trial and error/googleing to make sure I have the exact right syntax for media queries.
