### ISSUE TITLE
Padding issues

### ISSUE THREAD

**Issue by nickngqs** [thoughtbot/neat#503]
Hi,

I'm trying out Neat 2.0. But just seems very hard to get simple thing like this to work.

Can i get any advice?

Because of how the new margin-left works. There will always be margin on the left side.

I want to achieve this using border-top inside the grid container

![achieve](https://cloud.githubusercontent.com/assets/3901903/19259719/c5a14b74-8fb6-11e6-9499-f5f9328b3f68.png)

But I got this instead
![result](https://cloud.githubusercontent.com/assets/3901903/19259721/c9fd1748-8fb6-11e6-86e6-e098c2337788.png)

How can I use the grid without using
`hr { @include grid-column(12) }`

**Comment by whmii** [comment]
Try wrapping the blocks in a container with `grid-collapse`

https://github.com/thoughtbot/neat/blob/neat-2.0.0/core/neat/mixins/_grid-collapse.scss
