### ISSUE TITLE
Dealing with multiple grids in layout

### ISSUE THREAD

**Issue by nickngqs** [thoughtbot/neat#510]
When dealing with multiple grids (with different gutters), I came into a problem when I want the outer gutters to align.

For example
```
$default-grid: ( columns: 12, gutter: 20px, media:null, )
$custom-grid: ( columns: 12, gutter: 60px, media: null, )
```
![ss](https://cloud.githubusercontent.com/assets/3901903/20163838/b8cc086c-a73a-11e6-9afc-4bfe215cb709.png)

I do think most common designs that rely on a grid actually align their very first and last column.

What's the best way to approach this? I tried a couple of ways and it doesn't seem to work. I think the best way is not to use the custom grid at all? And add padding to give the illusion of spacing?

Will there be a functionality to consume very specific columns? Currently the grid-collapse doesn't do much.

**Comment by kgcreative** [comment]
Grid-collapse basically consumes the gutters. If you wanted to manually do so, you can do it by
scss:
`margin left: ($gutter * -1);
margin-right: ($gutter *-1);
width: calc(100% + #{$gutter * 2});`
