### ISSUE TITLE
suspenders fresh + neat mixin = undefined mixin

### ISSUE THREAD

**Issue by ChrisCPO** [thoughtbot/neat#515]
Hey started a new app using suspenders. I probably missed some configuration.
I'm getting an undefined mixin on a Neat mixin.  
Log error:
```ruby
ActionView::Template::Error (Undefined mixin 'outer-container'.):
```

I have added grid-settings file to application.scss
```
@import "bourbon";
@import "grid-settings";
@import "neat";
```

file tree: 
```
└── stylesheets
    ├── application.scss
    ├── base
    │   ├── _base.scss
    │   ├── _buttons.scss
    │   ├── _forms.scss
    │   ├── _layout.scss
    │   ├── _lists.scss
    │   ├── _media.scss
    │   ├── _tables.scss
    │   ├── _typography.scss
    │   └── _variables.scss
    ├── components
    │   ├── _app-header.scss
    │   ├── _container.scss
    │   └── _flashes.scss
    └── _grid-settings.scss
```

then _container.scss
```
.container {
  @include outer-container;
}
```

**Comment by kgcreative** [comment]
Are bourbon and neat in your scss include paths?

**Comment by ChrisCPO** [comment]
They should be, I used tbots suspenders https://github.com/thoughtbot/suspenders to bootstrap my app.

**Comment by kgcreative** [comment]
If you are using suspernders v. 1.43.0 (November 8, 2016):

Note that the working versions of bourbon and neat are:
Update Bourbon to 5.0.0.beta.7
Update Neat to 2.0.0.beta.1

In Neat 2.0, outer-container has been deprecated, in favor of grid-container and grid-collapse. See  http://neat.netlify.com/docs/latest/

**Comment by tysongach** [comment]
> In Neat 2.0, outer-container has been deprecated, in favor of grid-container and grid-collapse. See http://neat.netlify.com/docs/latest/

Correct, Neat 2.0 is a major re-write and `outer-container` has been removed/replaced. Please downgrade to Neat 1.x, or reference the [Neat 2.0 docs](http://neat.netlify.com/docs/latest/) for which mixins to use.
