### ISSUE TITLE
[QUESTION] Installing bourbon-neat via npm installs all node-sass locally

### ISSUE THREAD

**Issue by Shoplifter** [thoughtbot/neat#516]
I have installed node-sass globally
`npm install -g node-sass`

If I installed bourbon-neat now, that would install node-sass again locally.
That is actually not new. But up until recently I was able to prevent this by setting a link to node-sass before installing bourbon-neat.
`npm link node-sass`
`npm install bourbon bourbon-neat --save`

Then I got a clean and slim installation of bourbon-neat, as I want it to be. But that does not work anymore.
Am I doing something wrong here?
My node-sass version is 4.0.0 and bourbon-neat seesms to require some 3.*. Maybe that's the reason?

**Comment by Milewski** [comment]
and.... why do it need to install node-sass as a dependency... i will handle the compilation myself.. i just installed it now and weirdly got node-sass together...

**Comment by Shoplifter** [comment]
@Milewski I agree. That would be preferred and actually expected behaviour. An npm installation should do the same thing as an installation with ruby gem.

**Comment by kazazor** [comment]
I also strongly agree.

More than that, currently the dependency is `^3.4` which means it uses `node-sass` < `4.1.1`.

Why do I care about it?
I'm using Alpine Linux for my Docker images, Docker is moving all of its official images from Ubuntu to Alpine.
`node-sass` add binaries for Alpine only in version `4.1.0`, so now when I'm installing `bourbon-neat` I'm getting an error that it couldn't install `node-sass`.

If `node-sass` wouldn't be a dependency that wouldn't have happened, or even just if the dependency was `^4.1.1`.

Can someone change that please?

**Comment by kazazor** [comment]
I've moved my discussion about Alpine linux to #519 so it will be a separate issue than the decision if to remove `node-sass` as a dependency or not.

**Comment by nowells** [comment]
I would definitely love to see this cleaned up, it is slowing down our npm installs for what should be pretty simple frontend components (our build tooling like webpack and node-sass are installed once, our frontend assets are installed multiple times)

**Comment by tysongach** [comment]
As of Neat 2.0, we no longer have any dependency on node-sass. The 1.x will remain with one because we don't want to introduce a breaking change.
