### ISSUE TITLE
npm bourbon-neat fails to install on Alpine Linux

### ISSUE THREAD

**Issue by kazazor** [thoughtbot/neat#519]
# What is the issue?

`bourbon-neat` fails to install on Alpine Linux using npm.

## Why is this important?

Alpine Linux is a lightweight linux that starts to be widely used. Docker is moving its offical images from Ubuntu to Alpine Linux.

## What is the issue?

`bourbon-neat` has a dependency to `node-sass` version `^3.4`. `node-sass` added binaries to Apline Linux only in version `4.1.0`.

## The needed solution

Change the dependency to be `^4.1.1`.

## Does it relates to any other issue?

Yes, #516 .
#516 talks about the need to completely remove the dependency to `node-sass` which will also solve this issue. I myself agree with it.

But, it seems that the conversation around #516 can take a while and won't necessary bring any change.
Since #516 is only a question and not an issue like the Alpine Linux one I've created a separate  issue to be tracked by others.

**Comment by tysongach** [comment]
Fixed in https://github.com/thoughtbot/neat/commit/439db5d4793df66398df40f78aba8039b4c4d945.
