### ISSUE TITLE
remove command on help page reads as "neat update"

### ISSUE THREAD

**Issue by caryhartline** [thoughtbot/neat#521]
In neat 1.8 using ruby 2.4 it shows `neat update` for the remove command. I'd send a pull request, but /lib/neat/generator.rb looks correct.

The help page in question below:

Commands:
  neat help [COMMAND]  # Describe available commands or one specific command
  neat install         # Install Neat into your project
  neat update          # Update Neat
  neat update          # Remove Neat
  neat version         # Show Neat version

**Comment by tysongach** [comment]
This was fixed via https://github.com/thoughtbot/neat/commit/a818981c7c172882383c8d4c6fc1638749d99019 in Neat 2.0. If you’d like to submit a PR for 1.8, we could cut a patch release with the fix.

**Comment by tysongach** [comment]
This is fixed in [v1.9.0](https://github.com/thoughtbot/neat/releases/tag/v1.9.0), which was released today.
