### ISSUE TITLE
[Proposal] [2.0] `collapse-grid-container()`

### ISSUE THREAD

**Issue by kgcreative** [thoughtbot/neat#528]
Premise:
I've been giving neat 2.0 a big test drive, and so far, i'm loving everything about it.

I'm finding, however, that there are some instances in which I want a container that collapses the gutters of it's parent, but I don't want that container to float: left.

This is a use case for `@include collapse-grid-container()`, which i've been testing out in my repo and seems to do what I need.

```
@mixin collapse-grid-container($grid: $neat-grid) {
  $_grid-gutter: _retrieve-neat-setting($grid, gutter);

  @if unit($_grid-gutter) == "%" {
    @warn "`grid-collapse` is not compatible with percentage based gutters.";
  }

  margin-#{_neat-float-direction($grid)}: -($_grid-gutter);
  margin-#{_neat-opposite-direction($grid)}: -($_grid-gutter);
  width: calc(100% + #{($_grid-gutter * 2)});

  &::after {
    clear: both;
    content: "";
    display: block;
  }
}
```

This takes some code from `$grid-container` and `$grid-collapse` to create a collapsed grid container that gives the appearance of being flushed with it's parent, without needing to resort to additional wrapper markup, and it leaves `$grid-collapse` it's proper place of existing as collapsed element inside the grid container proper.

I can submit a PR

**Comment by whmii** [comment]
@kgcreative Thanks for the notes here. this actually makes me realize that 1 issue is that *currently* `grid-collapse()` floats when it doesn't actually need to. it would function completely fine w/o being floated (assuming it was on an object that was `display: block;`). 

In that context, you could effectively do something like…

```scss
.my-cool-container {
  @include grid-container;
  @include grid-collapse;
}
```

…and have an unfloated, collapsed container.

I like keeping them separate just under the idea of single principals of responsibility, but if you would like to post a pr for removing float, I would be more than happy to merge it (after I get a sec to make sure I'm not missing something 😉 ). I think this change should get merged before friday's release.

**Comment by kgcreative** [comment]
@whmii - Done. PR sent.

**Comment by kgcreative** [comment]
Re:
>In that context, you could effectively do something like…

>```.my-cool-container {
  @include grid-container;
  @include grid-collapse;
}```
> …and have an unfloated, collapsed container.
> - whmii

This is exactly what I was trying to achieve, and that `float` kept tripping me up. I assumed it was there for a reason, but if we can kill it, then it solves the issue.

**Comment by whmii** [comment]
It was likely just a vestigial bit of code since collapse went through a lot of iterations before it landed on what it is now.

**Comment by kgcreative** [comment]
Closing issue now that PR is merged.
