### ISSUE TITLE
Confused by new syntax

### ISSUE THREAD

**Issue by MikeHarrison** [thoughtbot/neat#549]
Sorry for filling up the issues with what is essentially a support request, but I am confused by the new syntax when it comes to producing my layouts. I would be happy to contribute to the docs as I think an example of how this works would be useful. My scenario is pretty straightforward:

- 6 blocks of content
- On screens smaller than 720px they should be two in a row
- On screens 720px and larger they should be three in a row
- Ideally I would like a larger gutter on the larger screen size

In vintage old-skool Bourbon / Neat I would be doing this:

```
$first-breakpoint-value:   480px;
$second-breakpoint-value:  720px;
$third-breakpoint-value:   980px;

$small-up:       new-breakpoint(min-width $first-breakpoint-value);
$medium-up:      new-breakpoint(min-width $second-breakpoint-value);
$large-up:       new-breakpoint(min-width $third-breakpoint-value);

$tiny-only:      new-breakpoint(max-width $first-breakpoint-value - 1);
$small-only:     new-breakpoint(min-width $first-breakpoint-value max-width $second-breakpoint-value);
$medium-only:    new-breakpoint(min-width $second-breakpoint-value + 1 max-width $third-breakpoint-value);

.container {
  @include outer-container;

  .content-block {
    @include media($tiny-only) {
      @include span-columns(6);
      @include omega(2n);
    }
    @include media($small-only) {
      @include span-columns(6);
      @include omega(2n);
    }
    @include media($medium-up) {
      @include span-columns(4);
      @include omega(3n);
    }
  }
}
```

This of course would not allow me to adjust the gutter size. I have been playing around with 2.0 for a while and can't work out how to replicate this using the new `$grid-media` setup.

New neat looks great, if someone could help me out with getting my head around this I am sure I will be properly up and running with it.

Thanks!

**Comment by kgcreative** [comment]
For the sake of brevity, i'm going to ONLY target the bullet point requirements. Keep in mind this is proto code, and i'm opting for longer names for ease of reading.

SCSS:
```
$media-medium-max: (
    columns: 12,
    gutter: 20px,
    media: 'only screen and (max-width: 719px)'
);
$media-large-min: (
    columns: 12,
    gutter: 40px,
    media: 720px
);
.container {
  @include grid-container;
  @include grid-collapse; // optional, if you want the grid container to consume the gutters

  .content-block {
    @include grid-media($media-medium-max) {
        @include grid-column(1 of 2);
    }

    @include grid-media($media-large-min) {
        @include grid-column(1 of 3);
    }
  }
}
```

**Comment by MikeHarrison** [comment]
@kgcreative thanks so much for taking the time, that makes sense. I was declaring an argument on the `grid-container` which was where I was going wrong I think. Now I understand how the `grid-media` thing works, and have a working example.

This now means I don't get the clearing I used to have with `omega`, so now if one of the content blocks has a lot more content in than others the flow is interrupted - I have attached an image to show what I mean. Is this just a fact of life with the new version?

Thanks again for your help

![screen shot 2017-02-23 at 23 43 30](https://cloud.githubusercontent.com/assets/6464063/23284169/fb0e7a04-fa21-11e6-9be4-1fc2c2d37c88.png)

**Comment by kgcreative** [comment]
Hi mike,

there are a couple of ways to deal with the clearing issue.

My recommendation would be, on the parent container,
```
.container {
    display: flex;
    flex-flow: row wrap;
    justify-content: flex-start;
    align-items: flex-start; // stretch for equal heights
    align-content: center;
    box-sizing: border-box;
}
```

If you want the orphans to auto center-align, look at this issue: https://github.com/thoughtbot/neat/issues/543

Optionally, I've created an omega mixin for neat 2.0 that both clears the floats, and allows for centered layouts to work properly, available here: https://github.com/kgcreative/neat-omega

**Comment by kgcreative** [comment]
the more I think about this, for clearing floats, I would either use flexbox, or you can simply add a single clear: left to a 2n + 1 selector. Since we don't need the margin:0 behavior from neat 1.x, then just clearing the float is all you need. That will also let you use complex selectors for this.

**Comment by Log1x** [comment]
why is there hesitance on adding your omega mixin into the core? that along with your tips in my thread from last night has neat 2.0 working beautifully now. 

maybe there's a cleaner approach, but I feel the omega mixin will be necessary on a vast majority of complex templates built with neat 2.0.

i for one vote it's implemented in to core. it's light weight, and effective.

**Comment by whmii** [comment]
@Log1x to clarify the argument a bit, we want to make sure that neat is as focused as possible. historically, neat really suffered from too many things/features. Looking at http://neat.bourbon.io/docs/1.8.0/ is a great example of this by just the sheer number of mixins alone.

Whenever someone is working with a grid system or other library it's super common to see "am I doing this right" or other language along those lines. I feel there's a real desire from people to use the product as intended, Independent of whether it actually works for them or not. In that way, adding mixins is an implicit "this is how you're supposed to do things" statement. I think @kgcreative is totally on point with his evaluation that there are just multiple ways of solving the same problem. I think that for some users a float clear practice would be better, while for other projects a flex box approach would be superior. It's important that neat work well with new CSS features like flex box and even potentially CSS grid spec,  but I don't ever want to give the impression that if someone uses flex box and neat 2.0 that they're somehow doing it wrong.

That's it I have no objection to adding that feature, I just wanted give a little bit of time for the library to breath and get more users up in the wild. That way we can evaluate best practices, and remain open to new solutions. There's kind of a little joke around the idea that "A feature is a promise you have to keep forever" but I think it's really applicable in open source projects with good versioning. Don't Something is introduced it Needs to be maintained basically until the project goes through a major version change. But obviously if lots of folks are using it find it to be effective Will incorporate it into core.

**Comment by MikeHarrison** [comment]
Thanks for the help @kgcreative. This is literally day 1 of using new Neat in the wild so I am just finding my feet and working out best practice. I am sure it is going to be great, I just need to level up a bit on how it works and get some boilerplates together for common layout tasks.

**Comment by kgcreative** [comment]
@log1x my Mixin breaks neats philosophy of single purpose mixins (out of convenience), but realy, it should be two. Calling it omega was more of a "old habits die hard" and "I know how omega works in 1.x so this will feel familiar" more than it was a properly architected solution.

there are SO many solutions to this, that proscrobing one method over another feels heavy handed to me.

**Comment by kgcreative** [comment]
@mikeharrison happy to help! it took me a bit to grok grid-media, but now that I do,  it's made a big difference on the types of layouts that are possible. Neat's simplicity makes it highly expendable and powerful.

**Comment by MikeHarrison** [comment]
Thanks for the help @kgcreative - think I am going to hit codepen when I get time and put some example layouts together, to get used to it

**Comment by whmii** [comment]
@MikeHarrison glad things worked out 👏 👏 👏 

Another great way to test stuff out is to pull down the neat repo and run the contrib site. Check out https://github.com/thoughtbot/neat/blob/master/CONTRIBUTING.md for more details. 👍
