### ISSUE TITLE
Can u get the old docs back somewhere please.?

### ISSUE THREAD

**Issue by marcelhadorn** [thoughtbot/neat#553]
Some are still using a pre v2 version of neat, and might not want to replace it on so many projects just to replace them from span-columns to grid-columns? What good reason would justify this change anyway?

**Comment by whmii** [comment]
The old docs are still there at

- http://neat.bourbon.io/docs/1.8.0/
- http://neat.bourbon.io/docs/1.7.4/
- etc

There is a link to them on the site but it's not super clear. I'll update the navigation so it's more clear

**Comment by marcelhadorn** [comment]
Thanks!
