### ISSUE TITLE
How to use the max-width property with grid-media?

### ISSUE THREAD

**Issue by joshukraine** [thoughtbot/neat#555]
Just getting started with Neat 2, and I'm trying to use the `grid-media` mixin. The [documentation](https://github.com/thoughtbot/neat/blob/v2.0.0/core/neat/mixins/_grid-media.scss) only shows output for min-width breakpoints. How do I specific that I want max-width?

When defining a custom grid, I've tried setting it to a string like so:

```
$neat-grid-tablet: (
  gutter: 2rem,
  media: "max-width: 500px",
);
```

But this behaves differently than I expect, outputting only the string `max-width` instead of a complete media query. In short, how do I (or can I?) use `grid-media` to output something like this:

```
@media only screen and (max-width: 1000px) {
  // code...
}
```

**Comment by kgcreative** [comment]
Almost got it. Grid media either takes a min width, or a string with the full media query. That allows you to be more verbose if you need more complex media queries.
```
$neat-grid-tablet: (
  gutter: 2rem,
  media: 'only screen and (max-width: 500px)',
);
```

**Comment by joshukraine** [comment]
@kgcreative Wonderful, thank you!
