### ISSUE TITLE
rails 5.1

### ISSUE THREAD

**Issue by glaszig** [thoughtbot/neat#556]
i'm on a pretty standard rails 5.1 app and just added neat 2.0 to the `Gemfile`.
after `bundle install` and `@import 'neat';` i get the following:

```

ActionView::Template::Error (couldn't find file '/usr/local/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/neat-2.0.0/core/neat/mixins/_grid-container.scss'
Checked in these paths:
  /vagrant/app/assets/config
  /vagrant/app/assets/images
  /vagrant/app/assets/javascripts
  /vagrant/app/assets/stylesheets
  /usr/local/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/coffee-rails-4.2.1/lib/assets/javascripts
  /usr/local/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/actioncable-5.1.0.beta1/lib/assets/compiled
  /usr/local/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/actionview-5.1.0.beta1/lib/assets/compiled
  /usr/local/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/turbolinks-source-5.0.0/lib/assets/javascripts
  /vagrant/vendor/node_modules):
     7:
     8:   <title>MyApp</title>
     9:   <%= csrf_meta_tags %>
    10:   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    11: </head>
    12:
    13: <body>
```

note: the `_grid-container.scss` file does indeed exist at that location.

**Comment by tysongach** [comment]
I’ve not dug into this at all, but want to point out that [Rails 5.1 is in beta](http://weblog.rubyonrails.org/2017/2/23/Rails-5-1-beta1/) and is not yet a stable release.

**Comment by johnrees** [comment]
Just ran into this issue with 5.1.0.rc1

As a quick/temporary fix I ran `bundle exec neat install` inside `app/assets/stylesheets`

then removed `gem 'neat'` from my `Gemfile`

and changed the statement in `application.scss` to `@import "neat/neat";`

**Comment by dgalarza** [comment]
Hi all, I just tried replicating the issue by starting up a fresh Rails 5.1 app and installing Neat 2.0.0. I have not been able to replicate the issue however.

Are you still seeing this in stable Rails 5.1?

**Comment by whmii** [comment]
Closing for now. Feel free to reopen if issue persists.
