### ISSUE TITLE
Examples are a little sparse!

### ISSUE THREAD

**Issue by shaunmac** [thoughtbot/neat#557]
The update looks great, just wondering if there's going to be more examples in the future?
The earlier version had a bunch, which really helped. Now I'm a little lost as it's hard to understand just the documentation by it self.

TLDR: Please... please add more examples

**Comment by apsolut** [comment]
I'm lost with **2.0.**
*How to use it with bourbon, as now I don't have neat-helpers etc...  right now I'm back to 1.8 and as it looks like I will need to change my workflow (re-integrate) neat in a different way...

**Comment by SimonFricker** [comment]
+1

**Comment by wardpenney** [comment]
Hey all, we've got a few more good examples on http://neat.bourbon.io/examples/ now, check it out! It is meant to read top-to-bottom, with each one addressing a core concept that gets a little more complex. LMKWYT

**Comment by apsolut** [comment]
Examples (they are good, even BEM)...  Now I think that 1.8 to 2.0 is not that easy, as I need to replace $column, $gutter, new-breakpoint, omega, grid-columns, span-columns **in my mind - to something**, I'm not against it at all (I just need better documentation and bunch of examples...) 
:heart: for all your hard work :gem:

**Comment by wardpenney** [comment]
@apsolut That is a good way to think about 1.x to 2.0 upgrading. Neat API from 1.x to 2.0 is a lot about custom grids (OK to nest ancestrally in the DOM, yet with different columns and gutters). I'll prioritize looking an example of an upgrade soon. 

But, if you're starting on an upgrade today, here's my gut-shot TLDR; 

1) look for changes to columns or gutters to the base Neat 1.x variables, those are going to signal you made a new grid map variable, and use it where it's relevant. 
2) text search for any `@include span-columns(1 of ` or `@include span-columns(1, ` (`scss`) to find places where your codebase changes the grid column context. That signals a new grid variable. Define it, then pass it in.
3) collapse works pretty much the same way (although under the hood is different)
