### ISSUE TITLE
visual and nested custom grids

### ISSUE THREAD

**Issue by ryandeussing** [thoughtbot/neat#559]
I came across a couple things that I believe can be better exhibited in the docs:

1. To use the visual grid in a custom grid, you need to specify *both* the color and the grid upon which to base measurements. This is in the docs but no explicit example is given and it took me a while to grok:

```scss
// within a media query that matches $my-custom-grid
.grid-container {
    @include grid-visual(yellow, $my-custom-grid);
  }
```

2. To nest grids, `grid-collapse` should be applied to a *child* of a column element, and also specify the custom grid if you're using one:

```scss
// within a media query that matches $my-custom-grid
.grid-column {
  .my-inner-grid-container {
    @include grid-collapse($my-custom-grid);
  }
}

```

It's not clear to me whether that child element must also be an actual `grid-container` (e.g. have the `@include grid-container` rule applied) or not. A visual example of nesting, with default and custom grids, would be super-helpful.

Thanks

**Comment by whmii** [comment]
related → https://github.com/thoughtbot/neat/issues/557

**Comment by ryandeussing** [comment]
I see some new examples have been added, thanks!

Some more niggling suggestions that I think could help:

- make each grid example a standalone page, rather then embedding them all in a page (which makes checking the source difficult)
- make each example responsive
- include standard html markup examples

I had a hell of a time using 2.0 with comps that were designed for 1.x conventions - I'd love to be able to show non-techincal designers the 2.0 examples pages and have them understand the way things work now.

**Comment by whmii** [comment]
The documentation has been updated as well as the examples. Also check out https://derekshirk.com/upgrading-working-new-neat-2-0-grid/ which is a nice writeup on the subject.

This is something we will continue to improve over time. I am going to close this issue for now as we continue to move forward on this.
