### ISSUE TITLE
Scrollbar bug in documentation (firefox).

### ISSUE THREAD

**Issue by Trost123** [thoughtbot/neat#560]
Open http://neat.bourbon.io/docs/latest/#grid-media in Firefox.
Or see the following screenshot:
http://prntscr.com/ejreob

I've inspected the cause:
http://prntscr.com/ejrezn
It seems "overflow-y" overrides "overflow";
If I disable the "overflow-y: scroll;" line, "overflow: -moz-scrollbars-none;" will work.

**Comment by whmii** [comment]
I had a look in firefox and firefox nightly and couldn't replicate this.

2 issues are:

1. what platform are you using? (mac/pc)
2. what version of firefox are you running

**Comment by mparienti** [comment]
Hi,

Same problem here with:
1. Firefox 52 (and previously with Firefox 51)
2. on a Debian (Linux) platforme amd64

**Comment by Trost123** [comment]
51.0.1 (64-bit) on windows 7.
Just updated to v52 - still happens.

**Comment by whmii** [comment]
I've updated a PR that addresses these issues https://github.com/thoughtbot/neat.bourbon.io/pull/45
