### ISSUE TITLE
Confusion around issues for neat the library vs neat the website.

### ISSUE THREAD

**Issue by whmii** [thoughtbot/neat#561]
There are a lot of issues on https://github.com/thoughtbot/neat/issues that have nothing to do with the library but instead are actually about https://github.com/thoughtbot/neat.bourbon.io

This is a communication problem and one I would like to fix.

**Comment by whmii** [comment]
In discussing with @georgebrock and @mike-burns, the current plan is to dissolve the issues on https://github.com/thoughtbot/neat.bourbon.io in favor of having everything on https://github.com/thoughtbot/neat

Then, we'll create a `website` (or whatever) label that we add to issues that pertain to the website.

**Comment by whmii** [comment]
The `website` label has been added to neat issues for those that pertain to the site.

issues on [thoughtbot/neat.bourbon.io](https://github.com/thoughtbot/neat.bourbon.io) has been removed.

**Comment by tysongach** [comment]
Good idea!
