### ISSUE TITLE
Add support for non es6 

### ISSUE THREAD

**Issue by whmii** [thoughtbot/neat#563]
> The JavaScript and the site is written in es6 which doesn't work and some browsers. I was looking at https://github.com/vast/middleman-es6 which seems to be an es6 babel that will TransFile that will transpile the coat into vanilla JavaScript.

---
Ported over due to https://github.com/thoughtbot/neat/issues/561
Originally appeared on https://github.com/thoughtbot/neat.bourbon.io/

**Comment by tysongach** [comment]
Is this issue still relevant? If we wait long enough, and browser support gets better, does this become a moot point?
