### ISSUE TITLE
Sort versions numerically in version drop-down

### ISSUE THREAD

**Issue by whmii** [thoughtbot/neat#565]
via @tysongach 

>  <img width="185" alt="bc4e0166-f79e-11e6-8462-78b4078460d9" src="https://cloud.githubusercontent.com/assets/2489247/24049362/257dc218-0b02-11e7-927e-d5f9d2043058.png">
---
Ported over due to https://github.com/thoughtbot/neat/issues/561
Originally appeared on https://github.com/thoughtbot/neat.bourbon.io/

**Comment by ssosina** [comment]
Not really sure I need to make this an issue but perhaps this is a spelling mistake. **"Incluting"**. 

![typo](https://cloud.githubusercontent.com/assets/2512405/24367678/75c942a4-1315-11e7-98e8-2105a5260b5f.png)

**Comment by tysongach** [comment]
@ssosina Can you please open a new Issue for that? Or, even better, do you want to submit a PR fixing that typo?

**Comment by JasonEtco** [comment]
Hey @tysongach, I'll tackle this! Am I correct in thinking that this issue should be in the [Neat site repository](https://github.com/thoughtbot/neat.bourbon.io)? The relevant markup/css is in there.
