### ISSUE TITLE
Conflict with bundled and "locked" versions of Neat

### ISSUE THREAD

**Issue by electricbrick** [thoughtbot/neat#567]
I'm experiencing a strange issue related to Neat that I cannot decipher. 

It seems that not all Neat mixins are available to me when I chose to install a "locked" version. This necessitates me also calling the bundled version in an import statement. When I remove the import statements for either the bundled or the locked/local version of Neat, compiling fails.

Here are my import statements:

```
// Bourbon and Bitters imports
@import "vendor/bourbon/bourbon";
@import "vendor/neat/neat";
@import "neat";
@import "vendor/bitters/base";
```

Here are the error codes:

1) When removing the import for the bundled version of Neat:

> Compass: Compiling failed with this error:     error /Users/tom/Sites/su-vvv/www/www.su.edu/wp-content/themes/su-swarm/assets/styles/style.scss (Line 5 of /Users/tom/Sites/su-vvv/www/www.su.edu/wp-content/themes/su-swarm/assets/styles/base/_base.scss: Undefined mixin 'grid-container'.)
> Compilation failed in 1 files.

2) When removing the import for the locked/local version of Neat:

> Compass: Compiling failed with this error:     error /Users/tom/Sites/su-vvv/www/www.su.edu/wp-content/themes/su-swarm/assets/styles/style.scss (Line 8 of /Users/tom/Sites/su-vvv/www/www.su.edu/wp-content/themes/su-swarm/assets/styles/components/_header.scss: Undefined mixin 'row'.)
> Compilation failed in 1 files.

**Comment by kgcreative** [comment]
1) `grid-container` is a `neat-2.x` mixin
2) `row` is a `neat-1.8.x` mixin

It seems like you have conflicting versions of neat in your stack, and that's why you're getting this issue. You need to either upgrade your stack to neat 2.0, or step back your bundled version of neat back to one of the 1.8x releases.

**Comment by whmii** [comment]
Here is the documentation for the 2 different versions that you were using:

- http://neat.bourbon.io/docs/1.8.0/
- http://neat.bourbon.io/docs/2.0.0/

**Comment by electricbrick** [comment]
@kgcreative @whmii Thanks guys, this took care of it. Going with 2.0.
