### ISSUE TITLE
Better Reference Documentation

### ISSUE THREAD

**Issue by digisavvy** [thoughtbot/neat#568]
Hey all,
I'm trying to get up and running on a project with Neat 2.0. I have a project that was already using it and I'm struggling with figuring out how to replace older functions/mixins and such. `outer-container;` and `span-columns;` are gone so it's hard to figure out what to use in their place. Obviously, I can read what's there and then trial and error things. It's just difficult. Are there plans to provide better reference material?

Thanks for all the work here. I'm excited!

**Comment by kgcreative** [comment]
Hi @digisavvy,

I'm not sure regarding the plans for documentation, but in the meantime, the 2.0 equivalent to `outer-container` -> `grid-container`, and `span-columns` -> `grid-column`

**Comment by mAAdhaTTah** [comment]
Related, but a "upgrade guide" of sorts would be really helpful.

**Comment by digisavvy** [comment]
Thanks @kgcreative! I did get myself sorted out and I do like how simplified Neat has become. An upgrade guide would be useful. I didn't have to change too much, just the functions noted there.
