### ISSUE TITLE
Guides and Examples

### ISSUE THREAD

**Issue by RobertBroley** [thoughtbot/neat#571]
I am new to Neat, so I want to know if it is possible if a guide was included such as Bootstrap and Foundation, like how to set up a project, and some videos would be really great. I have also noticed in version 2.0 there seems to be less features, than the earlier version.

**Comment by whmii** [comment]
@RobertBartnicki  Here are some resources you should check out

1. How the grid 'works' → https://robots.thoughtbot.com/building-the-future-of-floated-css-grids
2. How to use it → https://robots.thoughtbot.com/the-release-of-neat-2-0-a-lightweight-and-flexible-sass-grid
3. Some basic examples → http://neat.bourbon.io/examples/
4. The documentation → http://neat.bourbon.io/docs/latest/

**Comment by RobertBroley** [comment]
@whmii 

Thanks for that I will check them out. So another question is I am okay to use some of the older features with 2.0? As in the documentation they are missing?

**Comment by whmii** [comment]
These have just changed names:
`span-columns` → `grid-column`
`outer-container` → `grid-container`

**Comment by RobertBroley** [comment]
Okay, Thanks I will try that out.
