### ISSUE TITLE
Weird image padding/margin issue

### ISSUE THREAD

**Issue by bgarrant** [thoughtbot/neat#576]
I am having an issue removing some spacing under a column.  It is about 6 pixels and won't remove.  Is it a bug?

```
// bluebox
section#bluebox-container {
  $bluebox-grid: (
    columns: 12,
    gutter: 6px,
  );
  $md-bluebox-grid: (
    columns: 12,
    gutter: 6px,
    media: 62em,
  );

  @include grid-container;
  .bluebox {
    margin: 6px 0;
    @include grid-column(6, $bluebox-grid);
    
    @include grid-media($md-bluebox-grid) {
      @include grid-column(3);
    }
   }
  .bar {
    background-color: $color-blue;
    color: $color-white;
    font-size: 24px;
    font-weight: 700;
    text-transform: uppercase;
    text-align: center;
    margin: 0 0 6px 0;
    padding: 16px;
  }
}
```

```
<section id="bluebox-container">
  <article class="bluebox">
    <div class="bar">Cool off on a hot summer day</div>
    <img src="image.jpg" alt="title">
  </article>

  <article class="bluebox">
    <div class="bar">Cool off on a hot summer day</div>
    <img src="image.jpg" alt="title">
  </article>

  <article class="bluebox">
    <div class="bar">Cool off on a hot summer day</div>
    <img src="image.jpg" alt="title">
  </article>

  <article class="bluebox">
    <div class="bar">Cool off on a hot summer day</div>
    <img src="image.jpg" alt="title">
  </article>
</section>
```

The white margin under the image should only be 6px.  For some reason some extra padding or margin is being added, or something is preventing the image from filling the space.

![capture](https://cloud.githubusercontent.com/assets/2436728/24461348/c798805e-146e-11e7-8362-74a93668d12f.PNG)

**Comment by bgarrant** [comment]
The image size is not the issue and I see no padding or margins.  What is causing the extra space?

![capture2](https://cloud.githubusercontent.com/assets/2436728/24461760/25248d2a-1470-11e7-8c7e-37333b5aa20d.PNG)

**Comment by whmii** [comment]
@bgarrant Have you set your images to `display: block;`? By default, they are `inline` which will typically cause them to have a little space below them.

**Comment by bgarrant** [comment]
That was part of it yes.  I think I have it working now.  Thanks as that was the part I was missing.
