### ISSUE TITLE
Are there any breakpoints?

### ISSUE THREAD

**Issue by bgarrant** [thoughtbot/neat#577]
Are there any breakpoints setup by default in Neat?  If not should I just setup something like this?

```
$sm: 48em;
$md: 62em;
$lg: 75em;
```

Also, any visibility classes?

**Comment by whmii** [comment]
Those breakpoints look good to me. Neat does not provide any defaults.

The final product might look something like:

```scss
$sm: 48em;
$md: 62em;
$lg: 75em;

$neat-grid:(
  gutter: 1rem,
);

$small-grid:(
  gutter: 1rem,
  media: $sm,
);

$medium-grid:(
  gutter: 1.5rem,
  media: $md,
);

$large-grid:(
  gutter: 2rem,
  media: $lg,
);
```

The gutter changes on the various grids are just to show an example of how you might change things on different screen sizes.

Not really sure what visual classes are.

**Comment by kgcreative** [comment]
Visual classes are things like .hide-on-lg - which neat does not provide by default either. There are so many different ways to set up your project, and neat doesn't look to prescribe those.

**Comment by bgarrant** [comment]
Exactly.  Wondering if anyone has written any of them.  Like .hide-on-small, .show-on-small.  I made these but they are very basic...
```
.invisible {
  visibility: hidden; }

.visible {
  visibility: visible; }

.display-block {
  display: block; }

.hide {
  display: none !important;
}

@media (max-width: 48em) {
  .hide-sm {
    display: none !important;
  }
}

@media (min-width: 48em) {
  .show-sm {
    display: none !important; 
  } 
}

@media print {
  .hide-print {
    display: none !important; 
  }
  .show-print {
    display: block !important; 
  } 
}
```

**Comment by bgarrant** [comment]
Also what is the best way to handle alignment?  Flex I know but any way to use Flex easily with Neat 2.0?

**Comment by bgarrant** [comment]
I have Bourbon 4.3.3. installed and like everything is depreciated.  Hoping version 5 brings them back once released.

**Comment by tysongach** [comment]
> I have Bourbon 4.3.3. installed and like everything is depreciated. Hoping version 5 brings them back once released.

Bourbon 5 removes all prefixing mixins. You can read more about that decision here: https://github.com/thoughtbot/bourbon/issues/702

**Comment by bgarrant** [comment]
I do not need an outer-container for the entire page do I?  I am just using containers on each row.  Is this the correct way to use Neat?  Does this syntax look correct?  Dont worry about the variable names as those are from our CMS.

```
<body>

<header id="navigation">
  {% include '_includes/_nav.html' %}
</header>

<main id="content">

<section id="jumbotron-container">
  {% set asset = entry.image.first() %}
  <div class="jumbotron" style="background-image:url({{ asset.getURL('headerImage') }}); background-repeat:no-repeat; background-size:cover; background-position: center;">
    <div class="jumbotron-box">
      <h2>LOOKING FOR A</h2>
      <h1>POOL THIS SEASON</h1>
      <h3>NOW IS THE TIME TO CALL BEFORE SPRING</h3>
    </div>
  </div>
</section>

<section id="bluebox-container">
  <article class="bluebox">
    <div class="bar">Cool off on a hot summer day</div>
    <img src="{{ asset.url('bodyImage') }}" alt="{{ asset.title }}">
  </article>

  <article class="bluebox">
    <div class="bar">Cool off on a hot summer day</div>
    <img src="{{ asset.url('bodyImage') }}" alt="{{ asset.title }}">
  </article>

  <article class="bluebox">
    <div class="bar">Cool off on a hot summer day</div>
    <img src="{{ asset.url('bodyImage') }}" alt="{{ asset.title }}">
  </article>

  <article class="bluebox">
    <div class="bar">Cool off on a hot summer day</div>
    <img src="{{ asset.url('bodyImage') }}" alt="{{ asset.title }}">
  </article>
</section>

</main>

<footer id="footer">
  <div class="footer">
    Copyright {{ siteName }}. Site by <a href="https://www.garrant.com" target="_blank">GARRANT</a>.
  </div>
</footer>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript" src="/js/nav.js"></script>

</body>
```

My CSS

```
// MAIN SECTION
// ---------------------------------------------------------------------------
// jumbotron

section#jumbotron-container {
  @include grid-container;
  .jumbotron {
  @include grid-column(12); 
    //height: 800px;
    width: 100%;
    padding: 0;
    margin: 0;
    overflow: hidden;
    .jumbotron-box {
      background: rgba(255, 255, 255, 0.7);
      margin: 10%;
      padding: 40px;
      h1,h2,h3 {
        text-transform: uppercase;
        text-align: center;
        font-weight: 700;
      }
      h2 {
        color: $color-blue;
        font-size: 86px;
        line-height: 94px;
      }
      h1 {
        color: $color-dblue;
        font-size: 124px;
        line-height: 130px;
      }
      h3 {
        color: $color-orange;
        font-size: 48px;
        line-height: 54px;
      }
    }
    .jumbotron-text {
      color: $color-dgray;
    }
  }
}

// bluebox
section#bluebox-container {
  $bluebox-grid: (
    columns: 12,
    gutter: 6px,
  );
  $md-bluebox-grid: (
    columns: 12,
    gutter: 6px,
    media: 62em,
  );
  @include grid-container;
  .bluebox {
    margin: 6px 0 0 0;
    @include grid-column(6, $bluebox-grid);
    
    @include grid-media($md-bluebox-grid) {
      @include grid-column(3);
    }
   }
  .bar {
    background-color: $color-blue;
    color: $color-white;
    font-size: 24px;
    font-weight: 700;
    text-transform: uppercase;
    text-align: center;
    margin: 0 0 6px 0;
    padding: 16px;
  }
}

// FOOTER
// ---------------------------------------------------------------------------
footer#footer {
  @include grid-container;
  background-color: $color-dgray;
  margin: 6px 0 0 0;
  .footer {
    @include grid-column(12);
    color: $color-white;
    font-size: 16px;
    font-weight: 700;
    text-transform: uppercase;
    padding: 16px 0 16px 0;
  }
}

```

**Comment by bgarrant** [comment]
You can see I have no outer-container as I want the site to expand full page width.  Is it recommend to stop that with a body wrapper at like 1920 with one such as:

```
body {
  max-width: 1920px;
  margin: 0 auto;
  width: 90%;
}
```

**Comment by bgarrant** [comment]
A container is basically a row wrapper correct? If I add an outer container on BODY I just need another container for each row of columns correct? Also, if I have a single column row do I still need to add the @include-grid-column(12)?

**Comment by wardpenney** [comment]
@bgarrant If you want a container that goes to full page width, remove the `max-width` and add `@include grid-container;`. Then you can make columns inside.

I also advice not putting a container on your body. For example, if you want a navbar at the top that has background color edge-to-edge, you want a unique container for that. Then when your page body starts, use the standard container. Think of sibling-level containers stacking on top of each other, all a child of the `body`.

**Comment by bgarrant** [comment]
Should I use a outside @include grid-container for the entire webpage or is it not needed? I was just going to wrap <header><main><footer> tags in a @include grid-container each for clearing floats. Is that OK?

**Comment by bgarrant** [comment]
I think I get it. Thanks.
