### ISSUE TITLE
Vertical Alignment possible?

### ISSUE THREAD

**Issue by bgarrant** [thoughtbot/neat#580]
How can I do vertical alignment? There used to be Flexbox mixins but I no longer see them. Can anyone help? I am using Neat 2.0. Thanks.

**Comment by wardpenney** [comment]
@bgarrant I don't believe Neat 1.8 contained anything for Flexbox or vertical alignment http://neat.bourbon.io/docs/1.8.0/. 

Depending on what you are trying to do, my high-level advice is to use Neat for dividing up the page, and use Flexbox perpendicular centering `align-items` for a pattern to be held *within* the Neat grid column you created.
