### ISSUE TITLE
Why is there a gutter on the left and right of the grid?

### ISSUE THREAD

**Issue by christhorp** [thoughtbot/neat#582]
I'm not sure I understand why there has to be a gutter on the left and right of the grid - referred to as 'Its share of the extra gutter' on [this page](https://robots.thoughtbot.com/building-the-future-of-floated-css-grids#the-push-left-grid)?

If it's truly necessary - how can we disable or work around it so there is no gutter on the sides?

Sorry if I've misunderstood something here.

**Comment by kgcreative** [comment]
You would use `grid-collapse` together with your `grid-container` to consume the gutters, so that visually the grid objects align with the rest of your content.

**Comment by christhorp** [comment]
Ok that's great. But it's strange that this isn't the default - I can't think why I would want gutters on the sides of my container.

**Comment by wardpenney** [comment]
@christhorp ohhh boy do I have a blog post for you! https://robots.thoughtbot.com/building-the-future-of-floated-css-grids

For a long time, there have been a few "ways" to do CSS grid frameworks. We felt that the dual gutter was more clear to work with, and had more expected behaivor than the left margin style. It gets real handy when you need to do `grid-collapse`.
