### ISSUE TITLE
Snippets and Autocomplete for Sublime Text

### ISSUE THREAD

**Issue by bgarrant** [thoughtbot/neat#584]
I know there used to be a package out there for Bourbon/Neat snippets and Autofill.  Does something like that exists for new versions of Bourbon or Neat in Sublime Text 3?

**Comment by whmii** [comment]
Sorry but this is not an issue with neat. Sublime text packages can be found at [https://packagecontrol.io](https://packagecontrol.io)

Only post issues that pertain directly to the Neat library. If you have general inquiries like the one above, post them to [https://stackoverflow.com](https://stackoverflow.com/). Github issues are not intended to be a discussion/support channel.

**Comment by bgarrant** [comment]
Thanks.  I will do that.
