### ISSUE TITLE
"File to import not found or unreadable: neat-helpers."

### ISSUE THREAD

**Issue by burmashave** [thoughtbot/neat#586]
Getting this error on upgrade to 2.0.0 in a Rails app from an auto-generated line in _grid-settings.scss:
`
@import "neat-helpers"; // or "../neat/neat-helpers" when not in Rails`

Is this no longer necessary?

**Comment by whmii** [comment]
Neat 2.0 no longer contains `"neat-helpers"`

all you need is `@import "neat";`

**Comment by burmashave** [comment]
Thanks!

**Comment by sixtyfive** [comment]
It'd be nice if Bourbon's `_grid-settings.scss` knew about this.

**Comment by tysongach** [comment]
@sixtyfive I think you mean Bitters’ old `_grid-settings` partial, but that was removed in Bitters 1.3.
