### ISSUE TITLE
Tablet media query not working? 

### ISSUE THREAD

**Issue by ntot** [thoughtbot/neat#587]
I am new to Neat 2.0 and having problems with media queries. 

**My code:**
`$neat-grid: (
 columns: 12,
 gutter: 2em,
);

$mobile: (
 columns: 12,
 gutter: 1em,
 media: 'screen and (min-width: 320px) and (max-width: 767px)'
);

$tablet: (
 columns: 12,
 gutter: 1.1em,
 media: 'screen and (min-width 768px max-width 1024px)'
);

.element {
 @include grid-column(3);

 @include grid-media($mobile){
   @include grid-column(4);
 }

 @include grid-media($tablet){
   @include grid-column(6);
 }
}`

It only shows desktop and mobile but tablet is never rendered.

**Comment by gretzky** [comment]
Could you reformat your code?

**Comment by kgcreative** [comment]
`'screen and (min-width 768px max-width 1024px)'`
Should be
`'screen and (min-width: 768px) and (max-width: 1024px)'`

**Comment by ntot** [comment]
Oh that was it, thank you so much :)
