### ISSUE TITLE
Unclosed parenthesis in media query expression

### ISSUE THREAD

**Issue by zapmedia** [thoughtbot/neat#588]
I using Bourbon Neat as a npm dependency. However, I am getting the following error:

line: 61
    column: 22
    formatted: Error: unclosed parenthesis in media query expression
        on line 61 of node_modules/bourbon-neat/core/neat/mixins/_grid-media.scss

when I'm using the following SCSS:

```
.main-col {
	@include grid-column(12);
	@include grid-media($neat-grid-tablet) {
		@include grid-column(8);
		margin-bottom: $base-spacing;
	}
	@include grid-media($neat-grid-mobile) {
		@include grid-column(6);
	}
}
```

**Comment by tysongach** [comment]
What Sass package are you using?

**Comment by zapmedia** [comment]
I'm using "gulp-sass": "^3.1.0"

**Comment by wardpenney** [comment]
Can you paste the CSS it produces? Also the variable definition for `$neat-grid-mobile`. Thanks!

**Comment by whmii** [comment]
@zapmedia yep, this is probably a formatting issue with your definition of `$neat-grid-mobile`. 

I double checked [_neat-parse-media.scss](https://github.com/thoughtbot/neat/blob/master/core/neat/functions/_neat-parse-media.scss) and [_grid-media.scss](https://github.com/thoughtbot/neat/blob/master/core/neat/mixins/_grid-media.scss) and there aren't any errant parentheses.

**Comment by whmii** [comment]
Closing for now. Reopen if you are still having issues.
