### ISSUE TITLE
Any place for more general discussion about Neat implementations?

### ISSUE THREAD

**Issue by christianmagill** [thoughtbot/neat#590]
I really like Neat 2.0!

For my own usage, I'd like to create a more structured approach to handling breakpoints and other settings which would allow me to create helper functions that take advantage of these assumptions.

One such mixin I can see being extremely useful is a mixin similar to gridle's universal mixin.

http://gridle.org/documentation#mixins-universal-mixin

I'd love to discuss this with people more involved with the project, but I'm not sure where the best place would be.

Much thanks,

**Comment by tysongach** [comment]
@christianmagill This is a good forum for that; feel free to discuss.

**Comment by wardpenney** [comment]
Impressive `mixin`, but I don't see the problem it solves. I prefer to see CSS rules when they only that, without any logic imposed. This seems like a needless port to regular old CSS separated by semi-colons.

**Comment by kgcreative** [comment]
@wardpenney - my original thought was "Oh, it simply moves cognitive load up by two obfuscation levels just to save me a couple of characters". I'm not sure i'd want that in my projects.

**Comment by christianmagill** [comment]
@wardpenney @kgcreative 

What I'm attempting to solve is the time it takes to discern what's happening with the grid. The more visual noise there is the harder things are to comprehend. While, it's easy enough when things are simple, as they get more complex your can quickly end up having to jump between many different places visually to really get a sense for what is going on. 

I think updating the grid-column and other mixins to respect the media property will help somewhat by allowing you to align your grids-column variations so they are easily readable.

It's the visual difference between reading this:

```

$small: (
   columns: 4,
   gutter: 10px,
);

$medium: (
   columns: 8,
   gutter: 20px,
   media: 700px,
);

$large: (
   columns: 12,
   gutter: 30px,
   media: 1000px
);

.column-1{
   @include grid-column(2, $small);
   @include grid-media($medium){
      @include grid-column(3);
   }
   @include grid-media($large){
      @include grid-column(5);
   }
}

.column-2{
   @include grid-column(2, $small);
   @include grid-media($medium){
      @include grid-column(5);
   }
   @include grid-media($large){
      @include grid-column(7);
   }
}
```

And this...

```

$small: (
   columns: 4,
   gutter: 10px,
);

$medium: (
   columns: 8,
   gutter: 20px,
   media: 700px,
);

$large: (
   columns: 12,
   gutter: 30px,
   media: 1000px
);

.column-1{
   @include grid-column(2, $small);
   @include grid-column(3, $medium);
   @include grid-column(5, $large)
}

.column-2{
  @include grid-column(2, $small);
  @include grid-column(5, $medium);
  @include grid-column(7, $large);
}
```

And that's still a fairly simple example.

I'm wondering if things might be even simpler with a wrapper function like...

```
$small: (
   columns: 4,
   gutter: 10px,
);

$medium: (
   columns: 8,
   gutter: 20px,
   media: 700px,
);

$large: (
   columns: 12,
   gutter: 30px,
   media: 1000px
);

.column-1{
   @include grid-col(2, $small, 3, $medium, 5, $large);
}

.column-2{
   @include grid-col(2, $small, 5, $medium, 7, $large);
}

```

As a side benefit of simplify the code, you'd also be able to display more code at one time, making things easier to understand as well.

**Comment by tysongach** [comment]
Personally, I don’t mind the verbosity because it more closely mimics the CSS which is output (the `grid-media` mixin is syntactically similar to CSS’s `@media`). By design, it’s not overly clever.

**Comment by kgcreative** [comment]
To me the wrapper option directly contradicts neats philosophy of single
purpose mixins. The second option is slightly easier to read, and the first
option is closer to the CSS. The second option makes sense to me from a
perspective of "oh, this grid context has a media option attached, it makes
sense for the Mixin to respect it"

**Comment by whmii** [comment]
@christianmagill I think this would make a great extension! Check out https://github.com/whmii/neat-class-generator as kind of a starter for how these are set up. I think you would be able to basically redefine the mixins to take multiple properties.

Up top in your example `grid-col(2, $small, 5, $medium, 7, $la… ` you have everything in a list. That'll probably cause you some headaches b/c in some of my experiments I have encountered tons of issues with lists of maps. There may be a way you can do it tho.

**Comment by christianmagill** [comment]
I ended up using this:

```
@mixin grid-res-col($args...){
  $num-of-cols: null;
  @each $arg in $args{
    @if(type-of($arg) == 'number'){
      $num-of-cols: $arg;
    }
    @else if(type-of($arg) == 'map'){
      @if($num-of-cols != null){
        @include grid-column($num-of-cols, $arg);
      }
      @else{
        @error "Number of columns not specified before grid map.";
      }
      $num-of-cols: null;
    }
  }
}
```
This is using the respect media query pull request.
