### ISSUE TITLE
Difficulty removing grid-span margins without Omega/Gutter mixins

### ISSUE THREAD

**Issue by curiouscrusher** [thoughtbot/neat#593]
The loss of the Omega and Gutter mixins has made working with nested grids... Difficult, to say the least. While grid-collapse is _essentially_ the same thing, it can't be used to solve the same problems. 

The issue I'm running into is this: I've got a grid container with two grid elements inside. Left element is span 4, right element is span 6 (Working with a 6 col grid). Layout is perfect, except I need to remove the left gutter on the 6 col element, and the right gutter on the 4 col element. Previously I could have just used the Gutter and/or Omega mixins to do this easily. If I try to use grid-collapse on my grid-spans, the margins get removed, but they also take over the whole width of the grid container as well. 

Is there something I'm missing in 2.0 to accomplish the same selective margin removal? Or is my only option just reverting to 1.8 and getting all the useful mixins back?

Here's an image to help illustrate my issue.
![omega](https://cloud.githubusercontent.com/assets/4745854/24721567/ba74739c-1a0e-11e7-8481-5e3a50bcda5c.png)

**Comment by kgcreative** [comment]
for this use case, you might need to nest one level deeper
proto-code:
````
.grid-span-4 {
  @include grid-column(4);
    .nested-container {
      @include grid-collapse {
      .categories, quicklinks {
        @include grid-column(1 of 2)
      }
    }
  }
}
```

**Comment by curiouscrusher** [comment]
Wow thanks for the quick reply! 

It worked, I'm not entirely sure how, but that's exactly what I was trying to have happen.
It seems like the new workflow is to `grid-collapse` the outer `grid-container`, then add the `grid-span` elements, and finally wrap those inner `grid-span` blocks and `grid-collapse` it. Is that fairly accurate?

**Comment by kgcreative** [comment]
`grid-collapse` is there to consume the gutters of whatever it's parent element is.

In your case, when you instanced a nested grid, that is a new grid object. Because you want to nest it, you need to consume its parent's gutters (in this case, it's parent grid-column)

**Comment by curiouscrusher** [comment]
Nice, thanks for the clarification. 

Gonna close this out now.
