### ISSUE TITLE
Function _neat-parse-media finished without @return)

### ISSUE THREAD

**Issue by electricbrick** [thoughtbot/neat#594]
I've tried to set up breakpoints according to the [March 27, 2017 post on Neat](https://robots.thoughtbot.com/the-release-of-neat-2-0-a-lightweight-and-flexible-sass-grid)

My variables look like this (I assume the syntax is correct via the tutorial, please correct me if I'm wrong):

```
$first-breakpoint-value: 768px;
$second-breakpoint-value: 1023px;
$third-breakpoint-value: 1200px;
$fourth-breakpoint-value: 1280px;

$sm-grid: (
  columns: 3,
  gutter: 20px,
  media: (max-width: $first-breakpoint-value),
  color: rgba(#00d4ff, 0.25),
  direction: ltr,
);

$md-grid: (
  columns: 6,
  gutter: 20px,
  media: (max-width: $second-breakpoint-value),
  color: rgba(#00d4ff, 0.25),
  direction: ltr,
);

$lg-grid: (
  columns: 12,
  gutter: 20px,
  media: (max-width: $third-breakpoint-value),
  color: rgba(#00d4ff, 0.25),
  direction: ltr,
);

$xl-grid: (
  columns: 12,
  gutter: 20px,
  media: (max-width: $fourth-breakpoint-value),
  color: rgba(#00d4ff, 0.25),
  direction: ltr,
);
```
Using Codekit as my compiler I'm receiving the following error:

> Compass: Compiling failed with this error:     error /path/_grid-media.scss: Function _neat-parse-media finished without @return)

**Comment by kgcreative** [comment]
max width should be:

`media: 'screen and (max-width: #{$first-breakpoint-value})'` (need to format it as a string, and escape the variable)

**Comment by electricbrick** [comment]
@kgcreative I attempted that and it doesn't correct the issue. I tried using pixel widths as well and compiling still fails. Is this a conflict with Compass?

**Comment by kgcreative** [comment]
Can you paste the code you tried?

**Comment by electricbrick** [comment]
I missed the single quotes you included in that code. What differentiates my usage vs. the example in the above Thoughtbot post that details media property usage like this:

`$max-width-grid: (
  media: (max-width: 1200px),
);

$small-only-grid: (
  media: (min-width:10px) and (max-width: 700px),
);

$print-only-grid: (
  media: print,
);`

**Comment by kgcreative** [comment]
@whmii - see above blog post. Y'all might need to clarify variable and string usage in neat media calls.

Specifically,
```
$small-only-grid: (
  media: (min-width:10px) and (max-width: 700px),
);
```

should probably be formatted as
```
$small-only-grid: (
  media: '(min-width:10px) and (max-width: 700px)',
);
```

so that:
```
$small-only-grid: (
  media: '(min-width:#{$sm-min}) and (max-width: #{$sm-max})',
);
```
will actually compile

**Comment by whmii** [comment]
@kgcreative good catch. I will issue a correction

**Comment by whmii** [comment]
The blog post that contained the error has been corrected 🔨
