### ISSUE TITLE
grid-container mixin doesn't use the passed-in map argument

### ISSUE THREAD

**Issue by mtthwcmpbll** [thoughtbot/neat#597]
The documentation for grid-container mixin says it takes a map as a parameter to specify the columns and gutter to use, and defaults to using the global `$neat-grid`.  The behavior of the mixin doesn't seem to change if I pass in a map that with different values than neat-grid, and looking at the source for grid-container it doesn't seem to use the parameter at all.  Is there a way to specify a different grid for a part of your page (to change the gutter for a specific area, for example)?

**Comment by kgcreative** [comment]
Are you expecting that grid container will output a media query, or are you expecting that grid container will output different gutters if called inside of a grid-media argument? Currently the second behavior is true, or, if passed a grid map, it uses the grid map to calculate gutters and total columns (but will not output a media query)

**Comment by mtthwcmpbll** [comment]
I'm not seeing any change in behavior with a custom grid versus not.

Test HTML:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link href="css/debug.css" rel="stylesheet">
  </head>
  <body>

    <div id="neat-grid">
      <div id="neat-col-1" class="box">column 1</div>
      <div id="neat-col-2" class="box">column 2</div>
      <div id="neat-col-3" class="box">column 3</div>
    </div>
    <div id="custom-grid">
      <div id="custom-col-1" class="box">column 1</div>
      <div id="custom-col-2" class="box">column 2</div>
      <div id="custom-col-3" class="box">column 3</div>
    </div>

  </body>
</html>
```

Test SASS (neat v2):
```
@import "bourbon";
@import "neat";

$neat-grid: (
  columns: 12,
  gutter: 20px,
);

$custom-grid: (
  columns: 12,
  gutter: 50px,
);

.box {
  border: 1px solid red;
  @include grid-column(4);
}

#neat-grid {
  @include grid-container;
  @include grid-visual;
}

#custom-grid {
  @include grid-container($custom-grid);
  @include grid-visual;
}
```

Output:
<img width="693" alt="localhost_5757_themes_snowfort-site_static_grid-container-test_html_ckcachecontrol_1491581128" src="https://cloud.githubusercontent.com/assets/226487/24808983/0564f466-1b8c-11e7-8dcc-09f832a388b0.png">

I expected this to change the columns to be narrower in the second grid, but there is no change.  Now that I'm looking through the other mixins, I see that I have to pass in the custom grid to all of them (not just the grid-container) and that results in the change I'd expect.  Sorry for the confusion folks!
