### ISSUE TITLE
Newer Neat

### ISSUE THREAD

**Issue by gibson135** [thoughtbot/neat#604]
Haven't used SASS in quite a long time. I see things have changed as stated on this page - http://neat.bourbon.io/changelog/

examples...

Mixins
direction-context has been removed
display-context has been removed
fill-parent has been removed

So how are these things done now? like they were with the page of examples awhile ago that looked like tables with blue boxes.

**Comment by whmii** [comment]
https://github.com/thoughtbot/neat#helpful-links contains links to demos and extensive guides on using neat including [demos](https://neat.bourbon.io/examples/) and [guides](https://robots.thoughtbot.com/the-release-of-neat-2-0-a-lightweight-and-flexible-sass-grid).
