### ISSUE TITLE
Cannot install latest version

### ISSUE THREAD

**Issue by thatryan** [thoughtbot/neat#608]
### Issue Summary

Hi there, on OS X 10.11, cannot get current version to install. Running the commands to install to directory `gem install neat` followed by `neat install` and all appears normal. Messages even says "fetching 2.0.0" etc, however once installed the files appear to be from version `1.7.2`

**Commands and messages for install**

![neat-install](https://user-images.githubusercontent.com/26583/27271522-15924ec0-547a-11e7-907f-cf8143e0096a.png)

**Files that show up post install**

![old-neat](https://user-images.githubusercontent.com/26583/27271535-2ac95ad6-547a-11e7-8276-14eeeab0420e.png)

What am I possibly messing up here lol.
Thank you.

**Comment by tysongach** [comment]
I’m unable to reproduce. Have you tried uninstalling all versions of the Neat gem (`gem uninstall neat`) and reinstalling? What is the output when you run `neat -v`?

**Comment by thatryan** [comment]
Sorry I meant to close this. I have no idea what the problem was, do terminals "cache"? I did do the uninstall and reinstall twice. Finally opened a new terminal window to try a different directory and it worked proper. I the `cd` back to working directory and it installed proper. So confused.

**Comment by tysongach** [comment]
No worries. I do think RubyGems does some caching. Perhaps you had 2.0 installed, but the CLI didn't catch onto it for some reason…

Glad you got it working!
