### ISSUE TITLE
Compatible with Google Web Starter Kit?

### ISSUE THREAD

**Issue by skube** [thoughtbot/neat#615]
### Issue Summary

When using Google Web Starter Kit and adding Neat results are unexpected.

### Steps to Reproduce

1. [Clone the Web Starter Kit](https://github.com/google/web-starter-kit) and `cd` into it.
2. Run `npm i -D node-neat`
3. In `gulpfile.babel.js` add `includePaths:` to the styles task
  ```
  .pipe($.sass({
      precision: 10,
      includePaths: require('node-neat').includePaths
    }).on('error', $.sass.logError))
```
4. In `basic.html` add path to styles: 
`<link rel="stylesheet" href="styles/main.css"> `
and some test markup
```
<div class="container">
    <div class="col">Lorem.</div>
    <div class="col">Ab.</div>
    <div class="col">Earum?</div>
</div>
```
5. In `main.scss` add
```
@import 'neat';
.container {
  @include grid-container;
  @include grid-visual;
  > .col {
    @include grid-column(2);
  }
}
```
6. Finally, run `gulp serve`

![screen shot 2017-06-26 at 7 31 47 pm](https://user-images.githubusercontent.com/146396/27564503-2dc9ce64-5aa6-11e7-85af-7a111babcaf3.png)

Expected to see 12 blue columns, not 13. Also, wider portions should be blue while gutters should be white. 

### Technical details:

- Neat Version: 2.0
- Build Tool or Environment: Gulp
- Browser/OS: Version 59.0.3071.109 (Official Build) (64-bit)

**Comment by tysongach** [comment]
This appears to be working correctly. The blue in the visual grid represents the gutters, not the columns. So you do have 12 columns showing. Is that correct, @whmii? I’ve not used the visual grid very much.

**Comment by skube** [comment]
Seems like something is amiss or I'm not understanding. When I try a [Codepen](https://codepen.io/skube/pen/gRXYyN) it seems the opposite, blues are the columns.

**Comment by tysongach** [comment]
Does the Google Web Starter Kit come packaged with other CSS? If there are no errors being thrown during compilation, perhaps there is just conflicting CSS that is affecting the rendering?

**Comment by tysongach** [comment]
No response; closing.
