### ISSUE TITLE
Documentation mismatched with code?

### ISSUE THREAD

**Issue by sixtyfive** [thoughtbot/neat#616]
### Issue Summary

Reading the neat docs, I can't use neat. Wondering if it should be, at this time, best practice to only use Bourbon/Neat/Bitters from their respective Github repositories?

### Steps to Reproduce

1. Read neat docs
2. Try to use `grid-container`
3. Find out it does not exist
4. Remember something about `outer-container`
5. Wonder why that works even though it's not mentioned in the docs

Really going for that shower now.

**Comment by sixtyfive** [comment]
It seems the documentation is already in sync with the Neat version here on Github.

**Comment by tysongach** [comment]
The `outer-container` mixin was removed in 2.0. A new mixin named `grid-container` is in 2.0 and accomplishes a similar task.

- Docs for 2.0 `grid-container`: http://neat.bourbon.io/docs/latest/#grid-container
- Docs for 1.x `outer-container`: http://neat.bourbon.io/docs/1.9.0/#outer-container

You can always view older documentation on the website via this dropdown: 

<img width="341" alt="screen shot 2017-06-27 at 19 20 20" src="https://user-images.githubusercontent.com/903327/27614151-d299e600-5b6d-11e7-9d2c-29480b95e8ed.png">

**Comment by sixtyfive** [comment]
Tyson, thank you and sorry for being so ignorant (or rather, blind) and not see that dropdown. Anyways, I've made the switch to the git versions now and I'm quite happy for it.
