### ISSUE TITLE
Can't reproduce nested grid method from Examples

### ISSUE THREAD

**Issue by shorty2240** [thoughtbot/neat#621]
### Issue Summary

Trying to set up nested grids as per the example but the reset grid goes full width. I am sure I am just missing something or misunderstanding something simple

As a side note, I find the examples a bit confusing on the Neat site. I can't tell if it's required that the class (eg sidebar-layout) matches the variable and having no experience with SLIM makes it a bit confusing, but that's by the by

### Steps to Reproduce

The only difference is that I declare the column widths prior to declaring the reset, I have recreated it here
https://codepen.io/anon/pen/JJaZmm

### Technical details:

- Neat Version: 2.0.0
- Browser/OS: Chrome/Windows

**Comment by kgcreative** [comment]
Content and features need to be sepparate elements. Grid collapse adjusts
margins and sets width to 100% plus margins. Grid columns adjusts width.
They are conflicting with each other. The grid object that collapses should
be instanced inside the 3 column grid object

Document
Sidebar
Content
Collapsed container
Nested grid objects

**Comment by kgcreative** [comment]
Arg. Email formatting fail. In your codepen, split content from features, (basically wrap your nested columns in an extra div called content) - and it works.

**Comment by kgcreative** [comment]
@shorty2240 - see https://codepen.io/kgcreative/pen/QgVZZG

**Comment by shorty2240** [comment]
Thanks for taking a look, that was very helpful
