### ISSUE TITLE
npm 2.x release?

### ISSUE THREAD

**Issue by tejasbubane** [thoughtbot/neat#624]
### Issue Summary

Version 2.x is not available on npm.

### Steps to Reproduce

https://www.npmjs.com/package/bourbon-neat - `1.9.0` is the latest version.

### Technical details:

Using neat in npm project and cannot afford to use rubygems just for this one dependency. The public API seems to be completely changed between 1.9 and 2.1 as per the docs [1](https://neat.bourbon.io/docs/1.9.0/) and [2](https://neat.bourbon.io/docs/latest/). In order to use the new version, I need it via npm.

**Comment by tejasbubane** [comment]
I think it has to do with the github release `1.9.0` tagged as latest.
When I do `yarn install bourbon-neat` I get `1.9.0` since that is the latest version as per npm.
But I can then upgrade it to `2.1.0`.

**Comment by tysongach** [comment]
Hi @tejasbubane!

For some silly reason, npm likes to operate off dates, not version numbers when it defines “latest.” We happened to release a fix to the 1.x cycle after we cut 2.1, but 2.1 is definitely the latest version available. You’ll need to specify the version number to get it.

You can always view the available versions using npm’s CLI:

```
npm view bourbon-neat versions
```

And to install a specific version:

```
npm install bourbon-neat@2.1.0
```

**Comment by tejasbubane** [comment]
@tysongach Thanks for looking into it! 👍  I was sure it must be some github-npm thing.

**Comment by code-chris** [comment]
Hi @tysongach ,
you could set the dist-tag manually to a new version like this:
```
npm dist-tag add bourbon-neat@2.1.0 latest
```

**Comment by robertmain** [comment]
Can this solution go in the docs somewhere? I've been pulling my hair out over this..
