### ISSUE TITLE
Error: Incompatible units: 'em' and ' '

### ISSUE THREAD

**Issue by agrancho** [thoughtbot/neat#625]
### Issue Summary

I had a project where I was using Neat and Bourbon, but were old versions (neat - 1.8 and bourbon 4.2.7) . I had to update them, but keep getting this error `Incompatible units: 'em' and ''.`

### Steps to Reproduce

1. Already had the gems installed in the project

2. Opened the console and:
`bundle update neat`

3. Got an error in the project `Incompatible units: 'em' and ''.`

4. Read an similar [issue here](https://github.com/thoughtbot/neat/issues/324) 
Opened the console and:
`bundle update bourbon`

5. The error  `Incompatible units: 'em' and ''.` remains

Also tried the solution on [this issue](https://github.com/thoughtbot/neat/issues/306) but did nothing.

### Technical details:

— Neat Version: neat (**2.1.0**)
— Bourbon Version: bourbon (**4.3.4**) 
— Build Tool or Environment: rails (**5.0.1**)

**Comment by tysongach** [comment]
@agrancho Hi!

Neat 2.0 was a major release with breaking changes from the 1.x release cycle. Upgrading from 1.8 to 2.1 would require quite a few changes to any Neat usage. Our [change log](https://github.com/thoughtbot/neat/blob/master/CHANGELOG.md) details all of these changes.

When you upgraded Neat, did you remove usage of Neat’s old 1.x features, and swap them for 2.x features?
