### ISSUE TITLE
Using Max Width in Grid Media or Custom Grids

### ISSUE THREAD

**Issue by digisavvy** [thoughtbot/neat#628]
This is more of a question. I have some use cases where I want to use a max-width instead of min-width. In the previous version of Neat you could do that by passing a text string `max-width 600px` and it worked. With version 2.x, that seems to have changed. I'd like to know what the thought process behind that was. Or, if I am doing it wrong I'd like to know how to do it right. =)

Here's what I tried.
```
		@include grid-media(max-width 767px) {
			max-width: 232px;
			margin: auto;
		}
```

**Comment by kgcreative** [comment]
```
$custom-grid: (
   columns: 12,
   media: "only screen and (max-width: 767px)",
   gutter: 10px,
);

@include grid-media($custom-grid) {
  max-width: 232px;
  margin: auto;
}
```

**Comment by digisavvy** [comment]
Thanks for your help!
