### ISSUE TITLE
outer-container not working properly, version 1.9.0

### ISSUE THREAD

**Issue by thatryan** [thoughtbot/neat#633]
Simple declaration for site here,

    .site-header,
    .site-content,
    .site-footer {
	    @include outer-container;
    }

However what should be in and `::after` is getting output in the main class, like so,

	.site-header,
	.site-content,
	.site-footer {
	  content: "";
	  display: table;
	  table-layout: fixed;
	  max-width: 1200px;
	  margin-left: auto;
	  margin-right: auto;
	}

**Comment by tysongach** [comment]
@thatryan  What was the issue?

**Comment by thatryan** [comment]
Sorry, this was my idiot fault, I had an old mixin `clearfix` that I had to remove and that fixed it.
