### ISSUE TITLE
Using 'border' and 'padding' can break simple grid-column set in Neat 2.1.0.

### ISSUE THREAD

**Issue by ergose** [thoughtbot/neat#636]
### Issue Summary
Confirmed in:
- Chrome Version 61.0.3163.100 (Official Build) (64-bit)
- Chromium Version 61.0.3163.79 (Official Build) Built on Ubuntu , running on elementary 0.4.1 (64-bit)
- Firefox 57.0b3 (64-bit) Mozilla Firefox for Ubuntu Canonical - 1.0

### Steps to Reproduce
I'm trying to reproduce the "Holy Grail" layout from here: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Using_CSS_flexible_boxes just to see what I can work with and I ran into an odd problem. I may be missing something, but I figured there would be a 'Neat' way (har har) to compensate for the unexpected behavior.

**Here's the SCSS I'm using with the HTML from the Mozilla page:**

```
$neat-grid: (
    columns: 12,
    gutter: 5px,
    direction: ltr,
);

body {
    //@include grid-container;
    font: 24px $font-stack-helvetica;
    background: #999999;
}

header, footer {
    //padding: 5px;
    min-height: 100px;
    //border: 1px solid #eebb55;
    border-radius: 7pt;
    background: #ffeebb;
    @include grid-column(12);
}

article {
    //padding: 5px;
    //border: 1px solid #cccc33;
    //padding: 3px;
    //box-shadow: inset 0 0 0 3px #cccc33;
    border-radius: 7pt;
    background: #dddd88;	
    @include grid-column(4);
}

nav {
    padding: 5px;
    border: 1px solid #8888bb;
    border-radius: 7pt;
    background: #ccccff;
    @include grid-column(4);
}

aside {
    //padding: 5px;
    //border: 1px solid #8888bb;
    border-radius: 7pt;
    background: #ccccff;
    @include grid-column(4);
}
```
As soon as I add the padding and border, the farthest right column kicks down below the 2nd one. 

**I also tried this as an alternative:**
```
padding: 3px;
box-shadow: inset 0 0 0 3px #cccc33;
```
On the alternative, as soon as I add the padding on one and then the last column kicks down once.

What would be the correct/intended way to handle this kind of situation in Neat 2.x if this isn't an issue with the grid-column calculation?

Thanks

### Technical details:

- Neat Version: 2.1.0
- Build Tool or Environment: Sass 3.5.1 (Bleeding Edge)
- Browser/OS: Elementary OS Loki

**Comment by ergose** [comment]
Just a thought, could something be added to grid-column like this to manually correct for these kinds of situations? i.e. `grid-column(4, 1px)` as a correction offset for the column with padding/border before calculating.

**Comment by ergose** [comment]
Nevermind. I get it now. grid-columns should not have borders or the like. I made an inner div and moved the border, etc. into it to do that. Worked like a charm. Closing issue.
```
.inner {
	padding: 5px;
	border: 5px solid #eebb55;
	border-radius: 7pt;
	min-height: 100px;
}

header, footer {
    //padding: 5px;
    //border: 1px solid #eebb55;
    //min-height: 100px;
    border-radius: 7pt;
    background: #ffeebb;
	@include grid-column(12);
}
```

**Comment by kgcreative** [comment]
You can. Use padding and borders with `border-collapse: collapse;`

**Comment by ergose** [comment]
Wow. I just finished refactoring my Sass and breaking the grid stuff off into it's one files. Talk about clean and tidy. Big thumbs up you all. Absolutely beautiful. It looks like I'm dropping Bootstrap.

Ha! You just responded as I was writing this. I'll go back and tidy it up even more then. Thanks @kgcreative
