### ISSUE TITLE
Can't display the visual grids

### ISSUE THREAD

**Issue by cocodrino** [thoughtbot/neat#637]
Hi guys, sorry if this is a repetitive question, but I've tried every single solution than I've found and any of them work for me.

I 've put 
```sass
$visual-grid: true;

//or 


$visual-grid: true !global;
```

after and before of 

```sass
@import "bourbon/bourbon";
@import "neat/neat";

```

also I've tried creating a sass file in the end of my main file and adding this code

```sass

// Neat Settings

$visual-grid: true !global;
$visual-grid-color: #faa;
$visual-grid-index: front;

```

but seems not work, please let me know if I'm doing something wrong and how can I fix it, thank you so much!!!...

**Comment by whmii** [comment]
👋 @cocodrino what version of neat are you using? if you are using 2.0+ than you need to use the visual grid mixin `@include grid-visual;`

If you are using 1.X then what you have looks right.
