### ISSUE TITLE
Help with layout and new syntax please

### ISSUE THREAD

**Issue by thatryan** [thoughtbot/neat#638]
I have a mixin that sets my content container,

	@mixin wrapper {
		@include grid-container;
		margin-left: auto;
		margin-right: auto;
		max-width: $max-width;
	}

and some of the Scss,

	.content-wrap {
		@include wrapper;
		@include grid-visual;
	}
	.branding {
		@include grid-column(4);
	}

	.nav{
		@include grid-column(8);
	}

Now as an example, a header section with a breadcrumb section below it,

	<header>
		<div class=".content-wrap">
			<div class="branding"></div>
			<div class="nav"></div>
		</div>
	</header>
	<div class="breadcrumbs">
		<div class=".content-wrap"></div>
	</div>

The `branding` and `nav` blocks both call `grid-column` so they get left margins added, however `breadcrumbs` has no grid column because it is full width. So the content becomes mis-aligned. Does that make sense?

Really could use some help understanding what is the proper way to do this now. 

Thank you.

**Comment by kgcreative** [comment]
Add `include grid-xollapse` to your wrapper Mixin, and remove the auto margin left/right

**Comment by kgcreative** [comment]
(Or, if you’re using a centered layout, you may need to instance a collapsed grid container inside your wrapper)

**Comment by thatryan** [comment]
Thank you, so I did your first suggestion and it basically just puts everything to left of browser. So I guess I am doing centered, like your second comment. Can you elaborate on that part a tad more please?

**Comment by kgcreative** [comment]
Hey @thatryan  - sorry for the delay on this. There are a couple ways of doing centered, containers, the easier is to use a max-width wrapper, and instance a collapsed container inside of that.

Here is a quick demo: https://codepen.io/kgcreative/pen/MrEbEz
