### ISSUE TITLE
Sticky footer?

### ISSUE THREAD

**Issue by Derjyn** [thoughtbot/neat#640]
Greetings,

I'm trying to wrap my head around getting a sticky footer working, gracefully.  Has anyone else found a good method for doing this with Neat?

**Comment by whmii** [comment]
@Derjyn That's probably outside of the constraints of Neat. Most of what we would think of as a sticky footer would pertain to JS and not css other than `position: fixed;` etc. There is a nice write-up at https://css-tricks.com/couple-takes-sticky-footer/ that outlines some of the standard ways this is done.

Neat deals mostly w/ positioning/sizing objects on the X axis (horizontally), where as sticky footers are more of a Y axis (vertical) positioning/sizing problem. Once a sticky footer has been created, Neat would be great for positioning navigation and other elements w/ in the footer. Here's an example of some working code for the navigation of https://neat.bourbon.io at https://github.com/thoughtbot/neat.bourbon.io/blob/master/source/assets/stylesheets/components/_site-nav.scss

Hope that helps.
