### ISSUE TITLE
Module build failed:    @return $n * $column-width + ($n - 1) * $gutter-width;

### ISSUE THREAD

**Issue by joshuataylor** [thoughtbot/neat#641]
### Issue Summary

Upgrading to bourbon 5.0.0, results in the following error when using `span-columns(12)`:

```
Module build failed: 
  @return $n * $column-width + ($n - 1) * $gutter-width;
                              ^
      Undefined operation: "11 times em(20)".
      in /home/josh/dev/frontend/node_modules/bourbon-neat/app/assets/stylesheets/grid/_private.scss (line 20, column 32)
```

### Steps to Reproduce

1. Have bourbon 5.0.0, bourbon-neat 1.9.x:
```
    "bourbon": "^5.0.0",
    "bourbon-neat": "^1.9.0",
```
2. Use `@include span-columns(12);`

### Technical details:

- Neat Version: 1.9?
- Build Tool or Environment: SCSS
- Browser/OS: Ubuntu 17.10

**Comment by joshuataylor** [comment]
This is because the following was elsewhere:
```
$gutter: em(20);
```

Maybe the error could include a warning about this, to ask the user to check if their gutter is in em?

https://github.com/thoughtbot/bourbon/issues/691

**Comment by kgcreative** [comment]
The gutter can be in em, but bourbon 5 deprecated the em() function.

So while `$gutter: em(20px);` wouldn’t work, `$gutter: 1.2em` does work. This is a bourbon upgrade path issue, not a neat issue.

**Comment by kgcreative** [comment]
(See https://www.bourbon.io/docs/migrating-from-v4-to-v5/ )

**Comment by joshuataylor** [comment]
Ah yes, sorry, the function being removed is the problem, not the fact the fact it doesn't take em's - sorry!
