### ISSUE TITLE
using paddings instead of margins for gutter

### ISSUE THREAD

**Issue by rstich** [thoughtbot/neat#642]
Currently its not possible to have an Element which uses paddings instead of margins. 
Which is sometimes useful to position elements inside another while still maintaining the correct gutters. 

Take a look at my fork, especially this commit and use it if you want to:
https://github.com/SamhammerAG/neat/commit/3320a880ccfcbe69bf2150297f55640a9dd7a387

**Comment by kgcreative** [comment]
Do you have an example use case for this? I’m curious as to the specific edge case this this is targeting

**Comment by rstich** [comment]
Hey, 

i have an Element which fills only about one third of the page (in width that is) and needs some background color. 

Inside of that Element i have Text and Icons which needs to be aligned to the main grid. 
So i need the column width of the main grid to be able to place that element correctly. 
But since i have only text elements (red inline) i need some way to use padding.

I can do this with stacked elements of course but then i need HTML just for Layout purposes which i want to avoid.

The bare minimum would be to have a way to calculate that values but just using padding is easier to use i think.

**Comment by code-chris** [comment]
why this was closed without any statement to the given use case?

**Comment by whmii** [comment]
@rstich At this time we aren't looking to add new features to Neat. TO this end we created the extension network [https://github.com/thoughtbot/neat/projects/1](https://github.com/thoughtbot/neat/projects/1). If you are interested in creating an extension, you can use https://github.com/whmii/neat-class-generator as a template. as soon as it's live, I'll add it to the project board
