### ISSUE TITLE
toggle the device mode

### ISSUE THREAD

**Issue by vinaykhegde** [thoughtbot/neat#645]
**html**
```html
<section>
<article class="widget"></article>
<article class="widget"></article>
<article class="widget"></article>
<article class="widget"></article>
</section>
```

**custom variable.sass**
```sass
$custom-grid-mobile: (columns: 12,gutter: 1rem,media: 'screen and (min-width: 320px) and (max-width: 767px)')
$custom-grid-tab: (columns: 12,gutter: 2rem,media: 'screen and (min-width: 768px) and (max-width: 1024px)')
```
**widget.sass**
```sass
    .widget
     +grid-column(3)
     +grid-media($custom-grid-tab)
      +grid-column(6)
     +grid-media($custom-grid-mobile)
      +grid-column(12)
```
I am nesting the custom grid where desktop view would get 3 column, tab with 6 column and mobile with 12 column. When I resize my browser in Chrome, all of my responsive design works perfectly. However, when I go into the developer tools and toggle the device mode, none of my mobile styling works.

**Comment by kgcreative** [comment]
Toggling device mode often requires a refresh. Chrome developer tools warn
of this. This is an issue with chrome, not with neat.

**Comment by vinaykhegde** [comment]
Thankyou @kgcreative
