### ISSUE TITLE
Deprecated Unescaped multiline strings

### ISSUE THREAD

**Issue by wbotelhos** [thoughtbot/neat#647]
### Issue Summary

```
DEPRECATION WARNING on line 22, column 11 of /Users/wbotelhos/workspace/danca/app/assets/stylesheets/vendor/neat/neat/mixins/_grid-container.scss:
Unescaped multiline strings are deprecated and will be removed in a future version of Sass.
To include a newline in a string, use "\a" or "\a " as in CSS.
```

### Steps to Reproduce

1. Run a Rails app using `neat 2.1.0` and will be logged in console

### Technical details:

- Neat Version: 2.1.0

**Comment by dikaio** [comment]
@wbotelhos This is fixed by accessing the repository directly.

`gem "neat", git: 'https://github.com/thoughtbot/neat.git'`

**Comment by wbotelhos** [comment]
Thanks @dikaio , a new release would be nice.

**Comment by whmii** [comment]
Working on that today. should be out shortly

**Comment by whmii** [comment]
@wbotelhos 3.o is now live on ruby gems and npm
an update to the docs will be out this afternoon

**Comment by wbotelhos** [comment]
Thank you, @whmii :)
