### ISSUE TITLE
NPM release

### ISSUE THREAD

**Issue by Toady00** [thoughtbot/neat#648]
### Issue Summary

It's been a over a year since 2.0.0 has been released. The latest tag version is 2.1.0. But the latest npm package is beta2. Do you plan on pushing any more new versions to npm or is that no longer a channel neat will be distributed by?

**Comment by kgcreative** [comment]
NPM is weird in what it considers “latest”. `"bourbon-neat": "^2.1.0",` in your package.json correctly pulls the latest version, as does `$ npm install bourbon-neat@2.1.0` via the CLI

**Comment by Toady00** [comment]
Ok. I just ran npm install naked without the version, assuming I'd get the
latest.

**Comment by kgcreative** [comment]
It’s probably good to nudge the team to do an incremental update to get NPM to refresh its “latest”

**Comment by kgcreative** [comment]
@whmii

**Comment by eballeste** [comment]
https://github.com/thoughtbot/neat/issues/624#issuecomment-329149181

i always trip up on this on every new project jajaja

**Comment by tysongach** [comment]
Is this issue no longer relevant now that v3.0 is out? cc: @whmii
