### ISSUE TITLE
npm install: installs bourbon-neat@1.9.1

### ISSUE THREAD

**Issue by eballeste** [thoughtbot/neat#660]
just did a fresh install via npm, got version 1.9.1, expected v 3.0

this is a continuation of closed issues #648 & #624

[solution that can only be done by owners:](https://github.com/thoughtbot/neat/issues/624#issuecomment-329149181)
```
npm dist-tag add bourbon-neat@3.0.0 latest
```

**Comment by eballeste** [comment]
just saw that 1.9.x was recently updated, npm install should install 3.x by default

**Comment by whmii** [comment]
@MikeSperone this is just how NPM works. Unfortunately NPM decides that it is going to install the 'newest' version, not by version number but by release date. It's a very annoying behavior, however it is out of our control. An update to version 3 will be released this week but if ever a minor change to 1.X is made. this issue will resurface.

**Comment by eballeste** [comment]
@whmii you can tell npm what to consider latest!

**Comment by eballeste** [comment]
@whmii https://docs.npmjs.com/cli/dist-tag

**Comment by whmii** [comment]
@eballeste updated https://www.npmjs.com/package/bourbon-neat
