### ISSUE TITLE
issue w/_neat-parse-columns  

### ISSUE THREAD

**Issue by ShaikhahMaasher** [thoughtbot/neat#664]
I faced an error when compiled Neat _Version: 3.0.0_.
```
Error: expected "(".
  } @else if length($span) == 2 or if length($span) >= 3 {
                                   ^
```
The problem with the second `if` in L:19 of `functions/_neat-parse-columns.scss`.

**Comment by whmii** [comment]
Welcome to Neat! 👋🎉


Please let us know what Build Tool or Environment you are using

**Comment by peterson-umoke** [comment]
am sorry, please has this new merge been pushed to npm
